Repository elastic/elastic-charts, pull requests merged in 2019-04, with the labels that each got.

#141 fix(areachart): fix misaligned rendering props
  src/components/react_canvas/area_geometries.tsx
  src/components/react_canvas/bar_geometries.tsx
  src/components/react_canvas/line_geometries.tsx
  src/components/react_canvas/utils/rendering_props_utils.test.ts
  src/components/react_canvas/utils/rendering_props_utils.ts
  stories/area_chart.tsx
Labels: :chart, bug, test

#146 fix(build): fix dependencies for kibana integration
  package.json
  yarn.lock
Labels: chore

#126 feat(annotations): render line annotations via LineAnnotation spec
  .storybook/config.ts
  src/components/_annotation.scss
  src/components/_chart.scss
  src/components/annotation_tooltips.tsx
  src/components/chart.tsx
  src/components/react_canvas/annotation.tsx
  src/components/react_canvas/reactive_chart.tsx
  src/lib/series/specs.ts
  src/lib/themes/theme.test.ts
  src/lib/themes/theme.ts
  src/lib/utils/ids.test.ts
  src/lib/utils/ids.ts
  src/specs/index.ts
  src/specs/line_annotation.tsx
  src/state/annotation_marker.test.tsx
  src/state/annotation_utils.test.ts
  src/state/annotation_utils.ts
  src/state/chart_state.test.ts
  src/state/chart_state.ts
  stories/annotations.tsx
Labels: :annotation, enhancement

#147 feat(legend): hide legend item if hideLegendItem on series spec is true
  src/components/_legend.scss
  src/components/legend.tsx
  src/components/legend_element.tsx
  src/lib/series/legend.test.ts
  src/lib/series/legend.ts
  src/lib/series/series.test.ts
  src/lib/series/specs.ts
  src/specs/area_series.tsx
  src/specs/bar_series.tsx
  src/specs/basic_series.tsx
  src/specs/line_series.tsx
  src/state/chart_state.test.ts
  src/state/test/interactions.test.ts
  stories/legend.tsx
Labels: :legend, enhancement

#153 test(canvas): test text bbox calculator on real canvas
  .storybook/config.ts
  jest.config.json
  package.json
  scripts/setup_enzyme.ts
  src/lib/axes/canvas_text_bbox_calculator.test.ts
  src/lib/axes/canvas_text_bbox_calculator.ts
  src/state/chart_state.test.ts
  src/state/chart_state.ts
  stories/interactions.tsx
  yarn.lock
Labels: :axis, bug

#151 fix(timescale): consider timezone on axis ticks
  .storybook/config.ts
  src/lib/axes/axis_utils.ts
  src/lib/series/domains/domain.ts
  src/lib/series/domains/x_domain.test.ts
  src/lib/series/domains/x_domain.ts
  src/lib/series/scales.ts
  src/lib/series/specs.ts
  src/lib/utils/scales/scale_continuous.test.ts
  src/lib/utils/scales/scale_continuous.ts
  src/lib/utils/scales/scale_time.test.ts
  src/lib/utils/scales/scales.ts
  src/state/chart_state.timescales.test.ts
  stories/scales.tsx
Labels: :axis, :data, :specs, bug

#156 docs: fix storybook missing stories
  .storybook/config.ts
  src/state/chart_state.ts
Labels: chore

#154 feat(line_annotation): add hideLines and hideTooltips props to spec
  src/lib/series/specs.ts
  src/specs/line_annotation.tsx
  src/state/annotation_utils.test.ts
  src/state/annotation_utils.ts
  stories/annotations.tsx
Labels: :annotation, enhancement

#155 feat(legend): display series value (dependent on hover) & sort in legend
  src/components/_legend.scss
  src/components/legend.tsx
  src/components/legend_element.tsx
  src/lib/series/legend.test.ts
  src/lib/series/legend.ts
  src/lib/series/series.test.ts
  src/lib/series/series.ts
  src/lib/series/specs.ts
  src/lib/series/tooltip.ts
  src/lib/utils/interactions.ts
  src/specs/settings.tsx
  src/state/chart_state.test.ts
  src/state/chart_state.ts
  stories/legend.tsx
Labels: :legend, enhancement

#159 test(settings): add coverage for spec mount & update
  src/specs/settings.test.tsx
Labels: test

#157 feat: add band area chart
  src/components/highlighter.tsx
  src/components/react_canvas/area_geometries.tsx
  src/components/react_canvas/utils/rendering_props_utils.test.ts
  src/components/react_canvas/utils/rendering_props_utils.ts
  src/lib/series/__snapshots__/series.test.ts.snap
  src/lib/series/domains/y_domain.test.ts
  src/lib/series/domains/y_domain.ts
  src/lib/series/nonstacked_series_utils.test.ts
  src/lib/series/nonstacked_series_utils.ts
  src/lib/series/rendering.areas.test.ts
  src/lib/series/rendering.bands.test.ts
  src/lib/series/rendering.bars.test.ts
  src/lib/series/rendering.lines.test.ts
  src/lib/series/rendering.test.ts
  src/lib/series/rendering.ts
  src/lib/series/scales.test.ts
  src/lib/series/series.test.ts
  src/lib/series/series.ts
  src/lib/series/specs.ts
  src/lib/series/stacked_series_utils.test.ts
  src/lib/series/stacked_series_utils.ts
  src/lib/series/tooltip.test.ts
  src/lib/series/tooltip.ts
  src/lib/utils/interactions.test.ts
  src/lib/utils/interactions.ts
  src/state/__snapshots__/utils.test.ts.snap
  src/state/annotation_marker.test.tsx
  src/state/chart_state.test.ts
  src/state/chart_state.timescales.test.ts
  src/state/chart_state.ts
  src/state/test/interactions.test.ts
  src/state/utils.ts
  stories/area_chart.tsx
  stories/bar_chart.tsx
  stories/mixed.tsx
Labels: :chart, enhancement, wip

#103 chore(csp): add CSP meta tag and nonce for styles
  .storybook/preview-head.html
  .storybook/theme_service.ts
  .storybook/webpack.config.js
Labels: chore

#166 fix(exports): fix missing exports for annotations
  src/index.ts
  stories/annotations.tsx
  stories/interactions.tsx
Labels: bug

#170 feat: allow individual series styling
  src/components/react_canvas/area_geometries.tsx
  src/components/react_canvas/bar_geometries.tsx
  src/components/react_canvas/line_geometries.tsx
  src/components/react_canvas/utils/rendering_props_utils.test.ts
  src/components/react_canvas/utils/rendering_props_utils.ts
  src/lib/series/rendering.test.ts
  src/lib/series/rendering.ts
  src/lib/series/specs.ts
  src/lib/themes/theme.ts
  src/state/utils.ts
  stories/styling.tsx
Labels: :chart, enhancement

#167 fix: remove old specs with changed ids
  src/specs/area_series.tsx
  src/specs/bar_series.tsx
  src/specs/line_series.tsx
  stories/area_chart.tsx
  stories/bar_chart.tsx
  stories/line_chart.tsx
Labels: :chart, bug

#172 fix: apply transform.x to area & line geometries
  src/components/react_canvas/area_geometries.tsx
  src/components/react_canvas/line_geometries.tsx
  src/components/react_canvas/utils/rendering_props_utils.test.ts
  src/components/react_canvas/utils/rendering_props_utils.ts
  stories/mixed.tsx
Labels: :chart, bug

#173 fix: cleanup example prop default values
  src/components/chart.tsx
  src/lib/series/specs.ts
  src/specs/basic_series.tsx
  src/specs/index.ts
  src/state/utils.ts
  stories/annotations.tsx
  stories/area_chart.tsx
  stories/axis.tsx
  stories/bar_chart.tsx
  stories/grid.tsx
  stories/interactions.tsx
  stories/legend.tsx
  stories/line_chart.tsx
  stories/mixed.tsx
  stories/rotations.tsx
  stories/scales.tsx
  stories/styling.tsx
  wiki/overview.md
Labels: :specs

#174 ci(jenkins): add base PR setup and test script
  .ci/run.sh
  .nvmrc
  .travis.yml
  package.json
Labels: chore

#187 fix: merge multi-group indexed geometry
  src/state/utils.test.ts
  src/state/utils.ts
  stories/axis.tsx
Labels: :interactions, bug

#192 fix(bars): remove border visibility based on bar width
  src/components/react_canvas/bar_geometries.tsx
Labels: :chart

#193 chore: add check to PR template for exports
  .github/pull_request_template.md
Labels: chore

#190 feat(scales): add paddings between bars
  src/lib/axes/axis_utils.ts
  src/lib/series/scales.ts
  src/lib/themes/dark_theme.ts
  src/lib/themes/light_theme.ts
  src/lib/themes/theme.test.ts
  src/lib/themes/theme.ts
  src/lib/utils/commons.test.ts
  src/lib/utils/commons.ts
  src/lib/utils/scales/scale_band.test.ts
  src/lib/utils/scales/scale_band.ts
  src/lib/utils/scales/scale_continuous.test.ts
  src/lib/utils/scales/scale_continuous.ts
  src/lib/utils/scales/scale_time.test.ts
  src/lib/utils/scales/scales.test.ts
  src/lib/utils/scales/scales.ts
  src/state/annotation_marker.test.tsx
  src/state/annotation_utils.test.ts
  src/state/chart_state.test.ts
  src/state/chart_state.ts
  src/state/crosshair_utils.linear_snap.test.ts
  src/state/crosshair_utils.ordinal_snap.test.ts
  src/state/crosshair_utils.ts
  src/state/test/interactions.test.ts
  src/state/utils.ts
  stories/area_chart.tsx
  stories/bar_chart.tsx
  stories/styling.tsx
Labels: :chart, :interactions, :styling, enhancement

#199 chore: add simple playground code to run examples locally
  .gitignore
  .playground/index.html
  .playground/index.tsx
  .playground/playgroud.tsx
  .playground/webpack.config.js
  package.json
  src/utils/data/formatters.ts
  yarn.lock
Labels: chore
