Repository elastic/elastic-charts, pull requests merged in 2019-10, with the labels that each got.

#391 feat(tooltip): allow postfix banded area series
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/store/utils.test.ts
  src/chart_types/xy_chart/store/utils.ts
  src/chart_types/xy_chart/tooltip/tooltip.test.ts
  src/chart_types/xy_chart/tooltip/tooltip.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/utils/accessor.ts
  stories/annotations.tsx
  stories/area_chart.tsx
Labels: :data

#401 build(eslint): enable linting hidden folders
  .eslintignore
Labels: chore

#398 Feat/banded legend values
  src/chart_types/xy_chart/legend/legend.test.ts
  src/chart_types/xy_chart/legend/legend.ts
  src/chart_types/xy_chart/rendering/rendering.test.ts
  src/chart_types/xy_chart/store/__snapshots__/utils.test.ts.snap
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/store/utils.test.ts
  src/chart_types/xy_chart/store/utils.ts
  src/chart_types/xy_chart/tooltip/tooltip.ts
  src/chart_types/xy_chart/utils/__snapshots__/series.test.ts.snap
  src/chart_types/xy_chart/utils/series.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/chart_types/xy_chart/utils/stacked_percent_series_utils.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.ts
  src/components/legend/legend.tsx
  stories/area_chart.tsx
Labels: :legend

#409 feat: fill multi-series with missing x values data points
  .playground/index.html
  .playground/playgroud.tsx
  src/chart_types/xy_chart/domains/x_domain.ts
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/store/utils.ts
  src/chart_types/xy_chart/utils/__snapshots__/series.test.ts.snap
  src/chart_types/xy_chart/utils/series.test.ts
  src/chart_types/xy_chart/utils/series.ts
  src/chart_types/xy_chart/utils/stacked_percent_series_utils.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.ts
  src/components/legend/legend.tsx
  src/components/react_canvas/reactive_chart.tsx
  src/utils/commons.ts
  stories/bar_chart.tsx
Labels: :chart, :data

#429 fix: resize observer loop limit exception
  src/components/chart_resizer.tsx
Labels: bug

#425 chore: adding pretty-quick commit hook
  package.json
  yarn.lock
Labels: chore

#437 test: add niceTimeFormatter tests
  .ci/run.sh
  jest.config.js
  jest.config.json
  jest.tz.config.js
  package.json
  src/utils/data/formatters.ts
  src/utils/data/formatters.tz.test.ts
  src/utils/data/formatters.tz.test.utc.ts
  wiki/testing.md
Labels: chore

#444 ci: add dynamic console and debugger lint rules
  .eslintignore
  .eslintrc.js
  .prettierignore
  .prettierrc.js
  .prettierrc.json
  package.json
  src/utils/scales/scale_continuous.test.ts
Labels: ci

#418 fix(tooltip): render tooltip on portal to avoid hidden overflows
  .playground/index.html
  .playground/playgroud.tsx
  integration/page_objects/common.ts
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-test-tooltip-and-rotation-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-tooltips-rotation-0-shows-tooltip-on-first-x-value-bottom-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-tooltips-rotation-0-shows-tooltip-on-first-x-value-top-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-tooltips-rotation-0-shows-tooltip-on-last-x-value-bottom-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-tooltips-rotation-0-shows-tooltip-on-last-x-value-top-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-tooltips-rotation-90-shows-tooltip-on-first-x-value-bottom-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-tooltips-rotation-90-shows-tooltip-on-first-x-value-top-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-tooltips-rotation-90-shows-tooltip-on-last-x-value-bottom-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-tooltips-rotation-90-shows-tooltip-on-last-x-value-top-1-snap.png
  integration/tests/interactions.test.ts
  src/chart_types/xy_chart/annotations/annotation_marker.test.tsx
  src/chart_types/xy_chart/annotations/annotation_tooltip.ts
  src/chart_types/xy_chart/annotations/annotation_utils.test.ts
  src/chart_types/xy_chart/annotations/annotation_utils.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.ts
  src/chart_types/xy_chart/specs/line_annotation.tsx
  src/chart_types/xy_chart/store/chart_state.interactions.test.ts
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/store/chart_state.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/components/_annotation.scss
  src/components/_tooltip.scss
  src/components/annotation_tooltips.tsx
  src/components/chart.tsx
  src/components/react_canvas/line_annotation.tsx
  src/components/react_canvas/reactive_chart.tsx
  src/components/react_canvas/rect_annotation.tsx
  src/components/tooltips.tsx
  src/utils/data_generators/data_generator.ts
  stories/bar_chart.tsx
Labels: :tooltip, enhancement

#447 fix: add clip paths to highlighter component
  .playground/index.html
  .playground/playgroud.tsx
  package.json
  src/components/highlighter.tsx
  yarn.lock
Labels: :chart, bug
