Repository elastic/elastic-charts, pull requests merged in 2019-08, with the labels that each got.

#276 fix(theme): restore original point radius values
  src/chart_types/xy_chart/store/utils.test.ts
  src/utils/themes/dark_theme.ts
  src/utils/themes/light_theme.ts
  src/utils/themes/theme.test.ts
Labels: :styling, chore

#277 build: update dependencies
  package.json
  yarn.lock
Labels: chore

#280 fix: disable tooltip when details or custom content is null
  src/chart_types/xy_chart/annotations/annotation_utils.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/components/annotation_tooltips.tsx
  src/index.ts
  stories/annotations.tsx
Labels: :annotation, bug

#283 fix(types): export missing types
  src/index.ts
Labels: chore

#284 ci: add semantic-release slack bot
  .releaserc.json
  package.json
  yarn.lock
Labels: chore

#274 fix(tooltip): fix overflow for long series names
  src/components/_tooltip.scss
  src/components/tooltips.tsx
Labels: :chart, :styling, bug

#286 chore: configure release slack message as markdown
  .releaserc.json
Labels: chore

#285 fix(tooltip): fix tooltip formatting for rotated charts
  src/chart_types/xy_chart/store/chart_state.interactions.test.ts
  src/chart_types/xy_chart/store/chart_state.ts
Labels: :interactions, bug

#271 feat(bar_chart): color overrides
  src/chart_types/xy_chart/domains/y_domain.ts
  src/chart_types/xy_chart/rendering/rendering.test.ts
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/store/utils.ts
  src/chart_types/xy_chart/utils/series.ts
  src/chart_types/xy_chart/utils/specs.ts
  stories/bar_chart.tsx
  wiki/overview.md
Labels: :styling, enhancement

#289 fix: handle splitted series with group value to 0
  src/chart_types/xy_chart/legend/legend.test.ts
  src/chart_types/xy_chart/legend/legend.ts
Labels: :legend, bug

#302 fix: shift bars independently from the specs order
  src/chart_types/xy_chart/store/utils.test.ts
  src/chart_types/xy_chart/store/utils.ts
Labels: bug

#309 chore: remove rogue console.log
  src/components/legend/legend.tsx
Labels: chore

#304 feat: add cursor sync mechanism
  .playground/playgroud.tsx
  src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.ts
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/store/chart_state.ts
  src/components/chart.tsx
  src/specs/index.ts
  src/specs/settings.test.tsx
  src/specs/settings.tsx
  src/utils/scales/scales.ts
Labels: :interactions, [TSVB], enhancement

#318 docs: update custom fill/stroke styles on storybook
  stories/styling.tsx
Labels: docs

#317 feat: add chart size type overrides
  .playground/index.html
  src/components/chart.tsx
  src/index.ts
  src/utils/chart_size.test.ts
  src/utils/chart_size.ts
  stories/styling.tsx
Labels: :chart, bug

#322 fix: reduce opacity for points when hovering over legend items
  src/components/react_canvas/area_geometries.tsx
  src/components/react_canvas/line_geometries.tsx
  src/components/react_canvas/utils/rendering_props_utils.test.ts
  src/components/react_canvas/utils/rendering_props_utils.ts
Labels: :interactions, :styling, bug

#327 fix(tooltip): fix duplicate key warning for band area charts
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/tooltip/tooltip.test.ts
  src/chart_types/xy_chart/tooltip/tooltip.ts
  src/chart_types/xy_chart/utils/interactions.ts
  src/chart_types/xy_chart/utils/series.ts
  src/components/tooltips.tsx
  stories/area_chart.tsx
Labels: :interactions, bug

#320 fix: remove clippings from chart
  src/components/react_canvas/reactive_chart.tsx
Labels: :styling, bug

#319 feat: customize number of axis ticks
  src/chart_types/xy_chart/annotations/annotation_marker.test.tsx
  src/chart_types/xy_chart/annotations/annotation_utils.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.ordinal_snap.test.ts
  src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  src/chart_types/xy_chart/rendering/rendering.bands.test.ts
  src/chart_types/xy_chart/rendering/rendering.bars.test.ts
  src/chart_types/xy_chart/rendering/rendering.lines.test.ts
  src/chart_types/xy_chart/store/chart_state.interactions.test.ts
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/store/utils.test.ts
  src/chart_types/xy_chart/store/utils.ts
  src/chart_types/xy_chart/utils/axis_utils.ts
  src/chart_types/xy_chart/utils/scales.test.ts
  src/chart_types/xy_chart/utils/scales.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/chart_types/xy_chart/utils/stacked_percent_series_utils.test.ts
  src/components/react_canvas/axis.tsx
  src/utils/scales/scale_continuous.test.ts
  src/utils/scales/scale_continuous.ts
  src/utils/scales/scale_time.test.ts
  src/utils/scales/scales.test.ts
  stories/axis.tsx
Labels: :axis, enhancement

#334 fix(tooltip): ie11 flex sizing
  .playground/playgroud.tsx
  package.json
  src/components/_tooltip.scss
Labels: :styling, bug

#333 feat(theme): base theme prop
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/store/chart_state.ts
  src/specs/settings.test.tsx
  src/specs/settings.tsx
  src/utils/themes/theme.ts
  stories/styling.tsx
Labels: :chart, :styling, enhancement

#331 fix: decuple brush cursor from chart rendering
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/store/chart_state.ts
  src/components/_container.scss
  src/components/chart.tsx
  src/components/chart_resizer.tsx
  src/components/react_canvas/chart_container.tsx
  src/components/react_canvas/reactive_chart.tsx
Labels: chore

#339 feat: hide tooltip when hover over lines
  .playground/playgroud.tsx
  src/chart_types/xy_chart/annotations/annotation_utils.test.ts
  src/chart_types/xy_chart/annotations/annotation_utils.ts
  src/chart_types/xy_chart/utils/specs.ts
  stories/annotations.tsx
Labels: :interactions, enhancement

#345 feat(theme): multiple-partials
  src/specs/settings.tsx
  src/utils/commons.test.ts
  src/utils/commons.ts
  src/utils/themes/theme.test.ts
  src/utils/themes/theme.ts
  stories/styling.tsx
Labels: :styling, enhancement

#348 feat: compute global y domain on multiple groups
  .playground/playgroud.tsx
  src/chart_types/xy_chart/domains/y_domain.ts
  src/chart_types/xy_chart/specs/area_series.tsx
  src/chart_types/xy_chart/specs/axis.tsx
  src/chart_types/xy_chart/specs/bar_series.tsx
  src/chart_types/xy_chart/specs/histogram_bar_series.tsx
  src/chart_types/xy_chart/specs/line_annotation.tsx
  src/chart_types/xy_chart/specs/line_series.tsx
  src/chart_types/xy_chart/specs/rect_annotation.tsx
  src/chart_types/xy_chart/utils/specs.ts
  src/components/react_canvas/area_geometries.tsx
Labels: :specs, enhancement

#346 fix(scales): bisect correctly on continuous scales
  .playground/index.html
  .playground/playgroud.tsx
  src/chart_types/xy_chart/annotations/annotation_utils.test.ts
  src/chart_types/xy_chart/annotations/annotation_utils.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.ts
  src/chart_types/xy_chart/store/chart_state.interactions.test.ts
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/store/chart_state.timescales.test.ts
  src/chart_types/xy_chart/store/chart_state.ts
  src/chart_types/xy_chart/utils/scales.test.ts
  src/components/chart.tsx
  src/components/crosshair.tsx
  src/utils/scales/scale_band.ts
  src/utils/scales/scale_continuous.test.ts
  src/utils/scales/scale_continuous.ts
  src/utils/scales/scale_time.test.ts
  src/utils/scales/scales.test.ts
  src/utils/scales/scales.ts
  src/utils/themes/light_theme.ts
  stories/interactions.tsx
Labels: :annotation, :interactions, bug

#349 fix(vertical_cursor): fix tooltip and external events for 1st datapoint
  .playground/playgroud.tsx
  src/chart_types/xy_chart/store/chart_state.ts
  src/chart_types/xy_chart/tooltip/tooltip.ts
  src/components/chart.tsx
  src/components/legend/legend.tsx
  src/components/react_canvas/chart_container.tsx
  src/components/react_canvas/reactive_chart.tsx
  src/utils/scales/scale_continuous.ts
Labels: :interactions, bug

#353 fix(crosshair): limit the width of the cursor band on edges
  .playground/playgroud.tsx
  src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.ts
Labels: :interactions, bug

#355 fix: clip overflowing rect/lines/areas
  .playground/playgroud.tsx
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/store/utils.test.ts
  src/components/react_canvas/area_geometries.tsx
  src/components/react_canvas/bar_geometries.tsx
  src/components/react_canvas/line_geometries.tsx
  src/components/react_canvas/reactive_chart.tsx
Labels: :chart, bug
