Repository elastic/elastic-charts, pull requests merged in 2019-11, with the labels that each got.

#443 feat(bar_spec): min bar render height
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-min-height-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-test-min-height-positive-and-negative-values-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/rendering/rendering.bars.test.ts
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/store/utils.ts
  src/chart_types/xy_chart/utils/specs.ts
  stories/bar_chart.tsx
Labels: :chart, :specs, enhancement

#402 refactor(typings): prepare for upgrade TS to 3.7
  .ci/jobs/defaults.yml
  integration/tsconfig.json
  src/chart_types/xy_chart/rendering/rendering.test.ts
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/utils/series.ts
  src/components/react_canvas/area_geometries.tsx
  src/components/react_canvas/bar_geometries.tsx
  src/components/react_canvas/line_geometries.tsx
  src/components/react_canvas/reactive_chart.tsx
  src/components/react_canvas/utils/rendering_props_utils.ts
  src/utils/themes/theme.ts
  src/utils/themes/theme_commons.ts
Labels: chore

#449 chore: remove useless conditional
  src/chart_types/xy_chart/domains/x_domain.ts
Labels: chore

#451 feat: add PNG export
  .playground/index.html
  .playground/playgroud.tsx
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-interactions-png-export-action-visually-looks-correct-1-snap.png
  src/components/chart.snap.test.ts
  src/components/chart.tsx
  src/components/react_canvas/chart_container.tsx
  src/components/react_canvas/reactive_chart.tsx
  stories/interactions.tsx
Labels: enhancement, wip

#461 build: update dev dependencies
  .eslintrc.js
  .huskyrc.js
  package.json
  src/chart_types/xy_chart/utils/fit_function.test.ts
  src/utils/data/formatters.tz.test.ts
  stories/styling.tsx
  yarn.lock
Labels: chore
