Repository elastic/elastic-charts, pull requests merged in 2019-12, with the labels that each got.

#484 fix(crosshair): hide horizontal line when the pointer is outside chart
  .playground/playgroud.tsx
  src/chart_types/xy_chart/crosshair/crosshair_line.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.ts
  src/chart_types/xy_chart/renderer/dom/crosshair.tsx
  src/chart_types/xy_chart/state/selectors/get_cursor_line.ts
Labels: bug, regression

#482 fix(highlighter): hide it when tooltip type is None
  .playground/playgroud.tsx
  src/chart_types/xy_chart/state/chart_state.interactions.test.ts
  src/chart_types/xy_chart/state/chart_state.tooltip.test.ts
  src/chart_types/xy_chart/state/selectors/get_specs.test.ts
  src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
  src/mocks/specs/specs.ts
  src/specs/settings.tsx
  src/utils/commons.test.ts
  src/utils/commons.ts
Labels: bug, regression

#485 build(deps): move react as peer dependency, upgrade Konva
  .eslintrc.js
  integration/jest-env-setup.ts
  integration/page_objects/common.ts
  package.json
  src/chart_types/xy_chart/renderer/canvas/area_geometries.tsx
  src/chart_types/xy_chart/renderer/canvas/bar_geometries.tsx
  src/chart_types/xy_chart/renderer/canvas/bar_values_utils.ts
  src/chart_types/xy_chart/renderer/canvas/line_geometries.tsx
  src/chart_types/xy_chart/renderer/canvas/utils/rendering_props_utils.ts
  src/components/chart.tsx
  src/components/react_canvas/globals.ts
  yarn.lock
Labels: chore

#490 fix(highlighter): clip path unique id
  .playground/playgroud.tsx
  src/chart_types/xy_chart/renderer/dom/highlighter.tsx
Labels: bug

#488 fix: render stacked bar with stringified values
  src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  src/chart_types/xy_chart/utils/__snapshots__/series.test.ts.snap
  src/chart_types/xy_chart/utils/series.test.ts
  src/chart_types/xy_chart/utils/series.ts
Labels: bug

#473 docs: upgrade storybook and add docs per chart
  .storybook/addons.ts
  .storybook/config.ts
  .storybook/preview-head.html
  .storybook/webpack.config.js
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-fitting-functions-non-stacked-series-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-stacked-with-separated-specs-same-naming-visually-looks-correct-2-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-single-data-chart-ordinal-visually-looks-correct-2-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-custom-series-colors-through-spec-props-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-multiple-custom-partial-themes-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-tick-label-padding-both-prop-and-theme-visually-looks-correct-2-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-linear-point-alignment-start-2-snap.png
  integration/tests/axis-stories.test.ts
  package.json
  stories/annotations.tsx
  stories/axis.tsx
  stories/bar_chart.tsx
  stories/common.ts
  stories/interactions.tsx
  stories/legend.tsx
  stories/styling.tsx
  yarn.lock
Labels: docs
