Repository elastic/elastic-charts, pull requests merged in 2019-09, with the labels that each got.

#365 feat(chart_state): add render change event
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/store/chart_state.ts
  src/index.ts
  src/specs/settings.test.tsx
  src/specs/settings.tsx
  stories/interactions.tsx
Labels: :interactions, enhancement

#257 feat(theme): add gridLineStyle to AxisConfig
  src/components/react_canvas/grid.tsx
  src/components/react_canvas/reactive_chart.tsx
  src/utils/themes/dark_theme.ts
  src/utils/themes/light_theme.ts
  src/utils/themes/theme.test.ts
  src/utils/themes/theme.ts
  stories/grid.tsx
Labels: :axis, wip

#377 build(tsconfig): update storybook and playground tsconfig
  .playground/tsconfig.json
  .storybook/tsconfig.json
Labels: chore, docs

#376 fix(reactive_chart): fix order of instantiation of onBruchEnd callback
  src/components/react_canvas/reactive_chart.tsx
Labels: :chart, bug

#370 feat(axis): option to hide duplicate axes
  src/chart_types/xy_chart/store/chart_state.test.ts
  src/chart_types/xy_chart/store/chart_state.ts
  src/components/react_canvas/reactive_chart.tsx
  src/specs/settings.test.tsx
  src/specs/settings.tsx
  stories/scales.tsx
Labels: :axis, [TSVB], enhancement

#374 feat(axis): add visibility to tick style
  src/utils/themes/dark_theme.ts
  src/utils/themes/light_theme.ts
  src/utils/themes/theme.ts
  stories/styling.tsx
Labels: :axis, enhancement

#382 docs: update polyfill info in consuming doc
  wiki/consuming.md
Labels: docs

#392 chore: correct changelog
  CHANGELOG.md
Labels: chore

#390 docs(theme): update theme styles with clarifying explaination
  src/utils/themes/theme.ts
Labels: docs

#384 fix: x-scale for linear band charts
  .playground/playgroud.tsx
  src/utils/scales/scale_continuous.test.ts
  src/utils/scales/scale_continuous.ts
Labels: :axis

#395 fix(rendering): out-of-domain rendering of points/bars/lines/areas
  .playground/playgroud.tsx
  src/chart_types/xy_chart/rendering/rendering.bars.test.ts
  src/chart_types/xy_chart/rendering/rendering.lines.test.ts
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/store/utils.test.ts
  src/utils/scales/scale_band.test.ts
  src/utils/scales/scale_band.ts
  src/utils/scales/scale_continuous.test.ts
  src/utils/scales/scale_continuous.ts
  src/utils/scales/scales.ts
Labels: :chart, bug
