Repository elastic/elastic-charts, pull requests merged in 2020-02, with the labels that each got.

#536 fix: empty domain error for ordinal x scale
  src/utils/domain.test.ts
  src/utils/domain.ts
Labels: bug

#542 fix(ie11): replace fast-deep-equal with an internal copy IE11 safe
  package.json
  src/chart_types/xy_chart/renderer/canvas/area_geometries.tsx
  src/chart_types/xy_chart/renderer/canvas/axis.tsx
  src/chart_types/xy_chart/renderer/canvas/bar_geometries.tsx
  src/chart_types/xy_chart/renderer/canvas/bar_values.tsx
  src/chart_types/xy_chart/renderer/canvas/grid.tsx
  src/chart_types/xy_chart/renderer/canvas/line_annotation.tsx
  src/chart_types/xy_chart/renderer/canvas/line_geometries.tsx
  src/chart_types/xy_chart/renderer/canvas/rect_annotation.tsx
  src/chart_types/xy_chart/specs/line_annotation.tsx
  src/components/chart_container.tsx
  src/components/icons/assets/dot.tsx
  src/components/icons/icon.tsx
  src/components/legend/legend_item.tsx
  src/components/react_canvas/grid.tsx
  src/utils/fast_deep_equal.ts
  yarn.lock
Labels: bug

#543 chore: IE11 smoke tests
  .github/workflows/smoke_tests.yaml
  browsers/browsers.test.ts
  browsers/jest.config.js
  browsers/setup.js
  browsers/teardown.js
  package.json
  yarn.lock
Labels: chore

#546 fix(ie11): replace fast-deep-equal with a IE11 safe ver (#542)
  package.json
  src/chart_types/xy_chart/renderer/canvas/area_geometries.tsx
  src/chart_types/xy_chart/renderer/canvas/axis.tsx
  src/chart_types/xy_chart/renderer/canvas/bar_geometries.tsx
  src/chart_types/xy_chart/renderer/canvas/bar_values.tsx
  src/chart_types/xy_chart/renderer/canvas/grid.tsx
  src/chart_types/xy_chart/renderer/canvas/line_annotation.tsx
  src/chart_types/xy_chart/renderer/canvas/line_geometries.tsx
  src/chart_types/xy_chart/renderer/canvas/rect_annotation.tsx
  src/chart_types/xy_chart/specs/line_annotation.tsx
  src/components/chart_container.tsx
  src/components/icons/assets/dot.tsx
  src/components/icons/icon.tsx
  src/components/legend/legend_item.tsx
  src/components/react_canvas/grid.tsx
  src/utils/fast_deep_equal.ts
  yarn.lock
Labels: backport

#516 chore: preparation for spec rendering order
  src/chart_types/xy_chart/renderer/dom/tooltips.tsx
  src/chart_types/xy_chart/state/chart_state.interactions.test.ts
  src/chart_types/xy_chart/state/chart_state.specs.test.ts
  src/chart_types/xy_chart/state/chart_state.timescales.test.ts
  src/chart_types/xy_chart/state/chart_state.tooltip.test.ts
  src/chart_types/xy_chart/state/selectors/get_annotation_tooltip_state.ts
  src/chart_types/xy_chart/state/selectors/get_legend_tooltip_values.ts
  src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
  src/chart_types/xy_chart/state/selectors/is_tooltip_visible.ts
  src/chart_types/xy_chart/tooltip/tooltip.ts
  src/specs/specs_parser.tsx
  src/state/actions/specs.ts
  src/state/chart_state.ts
Labels: chore

#552 docs: fix filterSeriesInTooltip predicate
  stories/bar_chart.tsx
Labels: docs

#563 fix: redux connect issue related to spec upserting
  src/state/spec_factory.ts
Labels: bug

#565 fix: redux connect memo issue related to spec upserting
  src/state/spec_factory.ts
Labels: backport

#539 feat: add series name settings
  .playground/playground.tsx
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-add-custom-full-and-sub-series-label-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-add-custom-series-name-formatting-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-add-custom-series-name-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-add-custom-sub-series-label-formatting-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-custom-series-naming-config-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/legend/legend.test.ts
  src/chart_types/xy_chart/legend/legend.ts
  src/chart_types/xy_chart/rendering/rendering.test.ts
  src/chart_types/xy_chart/state/chart_state.specs.test.ts
  src/chart_types/xy_chart/state/chart_state.test.ts
  src/chart_types/xy_chart/state/utils.test.ts
  src/chart_types/xy_chart/tooltip/tooltip.ts
  src/chart_types/xy_chart/utils/series.test.ts
  src/chart_types/xy_chart/utils/series.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/mocks/series/seriesIdentifiers.ts
  stories/styling.tsx
Labels: :legend, :tooltip, enhancement

#572 test: update VRT baselines with fixed random generators
  docs/1-Typesofchart/1-Area.mdx
  docs/1-Typesofchart/4-Sunburts.mdx
  docs/1-Typesofchart/8-Donut.mdx
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-band-area-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-axis-fit-domain-to-extent-in-y-axis-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-axis-w-many-tick-labels-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-band-bar-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-with-high-data-volume-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-chart-size-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-multiple-custom-partial-themes-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-partial-custom-theme-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-partial-custom-theme-with-base-theme-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-theme-style-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/area-stories-test-ts-area-series-stories-accessor-formats-should-show-custom-format-1-snap.png
  integration/tests/__image_snapshots__/axis-stories-test-ts-axis-stories-should-render-tick-padding-1-snap.png
  src/mocks/utils.ts
  stories/area_chart.tsx
  stories/bar_chart.tsx
  stories/sunburst.tsx
  stories/treemap.tsx
Labels: test, visual testing

#550 fix: add snake case check for filenames
  .eslintrc.js
  integration/jest.config.js
  integration/jest_env_setup.ts
  integration/jest_puppeteer.config.js
  integration/page_objects/common.ts
  integration/tests/annotations_stories.test.ts
  integration/tests/area_stories.test.ts
  integration/tests/axis_stories.test.ts
  integration/tests/bar_stories.test.ts
  integration/tests/legend_stories.test.ts
  integration/tests/line_stories.test.ts
  integration/tests/mixed_stories.test.ts
  package.json
  src/chart_types/xy_chart/state/utils.test.ts
  src/chart_types/xy_chart/utils/series.test.ts
  src/mocks/series/series_identifiers.ts
  yarn.lock
Labels: chore, test

#574 feat: allow function x accessors
  src/chart_types/xy_chart/utils/__snapshots__/series.test.ts.snap
  src/chart_types/xy_chart/utils/series.test.ts
  src/chart_types/xy_chart/utils/series.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/utils/accessor.ts
Labels: vislib

#545 feat(legend): allow color picker component
  .eslintrc.js
  .storybook/style.scss
  integration/jest.config.js
  integration/page_objects/common.ts
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-legend-color-picker-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/legend-stories-test-ts-legend-stories-should-render-color-picker-on-mouse-click-1-snap.png
  integration/tests/legend_stories.test.ts
  package.json
  scripts/setup_enzyme.ts
  src/chart_types/partition_chart/layout/utils/calcs.ts
  src/chart_types/xy_chart/annotations/annotation_utils.ts
  src/chart_types/xy_chart/legend/legend.ts
  src/chart_types/xy_chart/renderer/canvas/axes/index.ts
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/state/chart_state.tsx
  src/chart_types/xy_chart/state/selectors/compute_legend.ts
  src/chart_types/xy_chart/state/selectors/get_legend_tooltip_values.ts
  src/chart_types/xy_chart/state/selectors/get_series_color_map.ts
  src/chart_types/xy_chart/state/selectors/merge_y_custom_domains.ts
  src/chart_types/xy_chart/state/utils.test.ts
  src/chart_types/xy_chart/state/utils.ts
  src/chart_types/xy_chart/tooltip/tooltip.ts
  src/chart_types/xy_chart/utils/series.test.ts
  src/chart_types/xy_chart/utils/series.ts
  src/components/chart.tsx
  src/components/legend/__snapshots__/legend.test.tsx.snap
  src/components/legend/_legend_item.scss
  src/components/legend/legend.test.tsx
  src/components/legend/legend.tsx
  src/components/legend/legend_item.tsx
  src/specs/settings.tsx
  src/state/actions/colors.ts
  src/state/actions/index.ts
  src/state/chart_state.ts
  src/state/selectors/get_legend_items.ts
  src/state/selectors/get_legend_items_values.ts
  src/utils/geometry.ts
  stories/legend/9_color_picker.tsx
  stories/legend/legend.stories.tsx
  yarn.lock
Labels: :legend, vislib

#554 feat: expose Specs types and clean up annotation types
  .playground/playground.tsx
  docs/1-Typesofchart/5-AnnotatingBars.mdx
  docs/2-ChartPropTables/12-AxisProps.md
  docs/2-ChartPropTables/14-LineProps.md
  docs/charts.tsx
  integration/tests/mixed_stories.test.ts
  src/chart_types/specs.ts
  src/chart_types/xy_chart/annotations/annotation_utils.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.ordinal_snap.test.ts
  src/chart_types/xy_chart/domains/y_domain.ts
  src/chart_types/xy_chart/legend/legend.test.ts
  src/chart_types/xy_chart/specs/line_annotation.tsx
  src/chart_types/xy_chart/utils/specs.ts
  src/index.ts
  src/mocks/series/series.ts
  src/mocks/series/series_identifiers.ts
  src/mocks/specs/specs.ts
  src/utils/ids.test.ts
  src/utils/ids.ts
  stories/annotations/rects/3_linear_line_chart.tsx
  stories/bar/23_bar_chart_2y2g.tsx
  stories/bar/24_tooltip_visibility.tsx
  stories/mixed/6_fitting.tsx
  stories/stylings/13_custom_series_name.tsx
  stories/stylings/13_custom_series_name_config.tsx
  stories/stylings/14_custom_series_name_formatting.tsx
  stories/stylings/16_style_accessor.tsx
  wiki/overview.md
Labels: chore
