Repository elastic/elastic-charts, pull requests merged in 2020-06, with the labels that each got.

#692 fix: missing dash style in line annotation
  api/charts.api.md
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-annotations-lines-styling-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/renderer/canvas/annotations/lines.ts
  src/utils/themes/theme.ts
  stories/annotations/lines/5_styling.tsx
Labels: :annotation, :xy, bug, regression

#629 fix(tooltip): show true opaque colors in tooltips
  .playground/playground.tsx
  integration/tests/__image_snapshots__/interactions-test-ts-interactions-tooltips-should-render-corrent-tooltip-for-split-and-y-accessors-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-interactions-tooltips-should-show-tooltip-on-sunburst-1-snap.png
  lint-staged.config.js
  src/components/tooltip/_tooltip.scss
  src/components/tooltip/tooltip.tsx
Labels: :styling, :tooltip

#697 feat: add missing screenshot functions
  src/chart_types/goal_chart/renderer/canvas/connected_component.tsx
  src/chart_types/goal_chart/state/chart_state.tsx
  src/chart_types/partition_chart/renderer/canvas/partition.tsx
  src/chart_types/partition_chart/state/chart_state.tsx
  stories/interactions/17_png_export.tsx
Labels: :export, enhancement

#693 fix: remove double rendering
  .playground/index.html
  .playground/playground.tsx
  package.json
  scripts/setup_enzyme.ts
  src/chart_types/goal_chart/renderer/canvas/connected_component.tsx
  src/chart_types/goal_chart/state/chart_state.tsx
  src/chart_types/partition_chart/layout/viewmodel/viewmodel.ts
  src/chart_types/partition_chart/renderer/canvas/partition.tsx
  src/chart_types/partition_chart/renderer/dom/highlighter_hover.tsx
  src/chart_types/partition_chart/renderer/dom/highlighter_legend.tsx
  src/chart_types/partition_chart/state/chart_state.tsx
  src/chart_types/xy_chart/domains/x_domain.ts
  src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
  src/chart_types/xy_chart/renderer/dom/annotations/annotations.tsx
  src/chart_types/xy_chart/renderer/dom/brush.tsx
  src/chart_types/xy_chart/renderer/dom/crosshair.tsx
  src/chart_types/xy_chart/renderer/dom/highlighter.tsx
  src/chart_types/xy_chart/state/chart_state.tsx
  src/components/__snapshots__/chart.test.tsx.snap
  src/components/chart.test.tsx
  src/components/chart.tsx
  src/components/chart_background.tsx
  src/components/chart_container.tsx
  src/components/chart_resizer.tsx
  src/components/legend/legend.test.tsx
  src/components/legend/legend.tsx
  src/components/tooltip/tooltip.tsx
  src/state/chart_state.ts
  src/state/selectors/get_internal_is_intialized.ts
  yarn.lock
Labels: :chart, bug, chore

#703 fix: path of stacked area series with missing values
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-test-stacked-with-missing-values-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-axes-custom-mixed-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/axis-stories-test-ts-axis-stories-should-render-with-domain-constraints-1-snap.png
  src/chart_types/xy_chart/utils/stacked_series_utils.ts
  stories/area/16_test_stacked_with_missing.tsx
  stories/area/area.stories.tsx
Labels: :xy, bug

#708 ci: lint only staged files
  lint-staged.config.js
  package.json
  yarn.lock
Labels: :ci

#704 fix: graceful scale fallbacks and warnings
  src/chart_types/partition_chart/renderer/canvas/partition.tsx
  src/chart_types/xy_chart/domains/x_domain.test.ts
  src/chart_types/xy_chart/domains/x_domain.ts
  src/chart_types/xy_chart/state/utils/utils.ts
  src/chart_types/xy_chart/utils/series.test.ts
  src/chart_types/xy_chart/utils/series.ts
  src/state/chart_state.ts
  src/utils/commons.ts
  src/utils/logger.ts
Labels: :xy

#709 fix(axis): rotated label positioning
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-axes-tick-label-rotation-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/axis-stories-test-ts-axis-stories-should-hide-bottom-axis-1-snap.png
  integration/tests/__image_snapshots__/axis-stories-test-ts-axis-stories-should-hide-left-axis-1-snap.png
  integration/tests/__image_snapshots__/axis-stories-test-ts-axis-stories-should-hide-top-axis-1-snap.png
  integration/tests/__image_snapshots__/axis-stories-test-ts-axis-stories-should-render-ticks-with-varied-rotations-1-snap.png
  src/chart_types/xy_chart/renderer/canvas/axes/title.ts
  stories/axes/2_tick_label_rotation.tsx
Labels: :axis, :xy, bug

#716 fix: apply positioning to hidden tooltip
  .storybook/style.scss
  integration/page_objects/common.ts
  src/components/_global.scss
  src/components/portal/_portal.scss
  src/components/portal/tooltip_portal.tsx
Labels: :tooltip, bug

#725 fix: move redux dev deps to optional
  package.json
Labels: :build, bug

#726 fix(partition): linked label on a larger than 180 degree slice
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-single-small-sice-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-single-very-small-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-with-linked-text-labels-visually-looks-correct-1-snap.png
  src/chart_types/partition_chart/layout/viewmodel/link_text_layout.ts
  stories/sunburst/6_pie_chart_linked_labels.tsx
  stories/sunburst/sunburst.stories.tsx
Labels: :partition

#721 ci: add license scan and split jobs
  .ci/global_setup.sh
  .ci/jobs/defaults.yml
  .ci/jobs/elastic+elastic-charts+pr-license-scan.yml
  .ci/jobs/elastic+elastic-charts+pr-lint.yml
  .ci/jobs/elastic+elastic-charts+pr-unit-tests.yml
  .ci/jobs/elastic+elastic-charts+pr-vrts.yml
  .ci/jobs/elastic+elastic-charts+pull-request.yml
  .ci/license_scan.sh
  .ci/lint.sh
  .ci/unit_tests.sh
  .ci/vrts.sh
  .fossa.yml
Labels: :ci, wip

#729 ci: fix status context
  .ci/jobs/elastic+elastic-charts+pull-request.yml
Labels: :ci

#731 ci: fix global setup path
  .ci/global_setup.sh
  .ci/jobs/defaults.yml
  .ci/license_scan.sh
  .ci/lint.sh
  .ci/unit_tests.sh
  .ci/vrts.sh
Labels: :ci

#732 ci: fix git refspec
  .ci/jobs/elastic+elastic-charts+pr-license-scan.yml
  .ci/jobs/elastic+elastic-charts+pr-lint.yml
  .ci/jobs/elastic+elastic-charts+pr-unit-tests.yml
  .ci/jobs/elastic+elastic-charts+pr-vrts.yml
Labels: :ci

#733 ci: split VRTs in two parts
  .ci/jobs/elastic+elastic-charts+pr-vrts-2.yml
  .ci/jobs/elastic+elastic-charts+pr-vrts.yml
  .ci/jobs/elastic+elastic-charts+pull-request.yml
  .ci/vrts.sh
Labels: :ci
