Repository elastic/elastic-charts, pull requests merged in 2020-07, with the labels that each got.

#739 fix: set uninitialized state when removeSpec action is called
  src/chart_types/xy_chart/state/chart_state.specs.test.ts
  src/state/chart_state.ts
Labels: :specs, bug

#737 feat(annotation): enable marker positioning on LineAnnotation
  api/charts.api.md
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-annotations-lines-styling-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/annotations/annotation_marker.test.tsx
  src/chart_types/xy_chart/annotations/line/dimensions.integration.test.ts
  src/chart_types/xy_chart/annotations/line/dimensions.ts
  src/chart_types/xy_chart/annotations/line/line.test.tsx
  src/chart_types/xy_chart/annotations/line/marker.test.tsx
  src/chart_types/xy_chart/annotations/line/tooltip.ts
  src/chart_types/xy_chart/annotations/line/types.ts
  src/chart_types/xy_chart/annotations/rect/tooltip.ts
  src/chart_types/xy_chart/annotations/utils.test.ts
  src/chart_types/xy_chart/annotations/utils.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/mocks/store/store.ts
  stories/annotations/lines/1_x_continuous.tsx
  stories/annotations/lines/2_x_ordinal.tsx
  stories/annotations/lines/3_x_time.tsx
  stories/annotations/lines/4_y_domain.tsx
Labels: :annotation, :xy, enhancement

#727 feat: custom annotation tooltip
  api/charts.api.md
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-annotations-lines-tooltip-options-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-annotations-rects-tooltip-options-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/annotations/rect/tooltip.ts
  src/chart_types/xy_chart/annotations/tooltip.ts
  src/chart_types/xy_chart/annotations/types.ts
  src/chart_types/xy_chart/renderer/dom/annotations/annotation_tooltip.tsx
  src/chart_types/xy_chart/renderer/dom/annotations/annotations.tsx
  src/chart_types/xy_chart/renderer/dom/annotations/tooltip_content.tsx
  src/chart_types/xy_chart/utils/specs.ts
  src/components/index.ts
  src/components/portal/tooltip_portal.tsx
  src/components/portal/types.ts
  src/components/portal/utils.ts
  src/components/tooltip/tooltip.tsx
  src/index.ts
  src/specs/settings.tsx
  stories/annotations/lines/7_tooltip_options.tsx
  stories/annotations/lines/line.stories.tsx
  stories/annotations/rects/4_styling.tsx
  stories/annotations/rects/5_tooltip_options.tsx
  stories/annotations/rects/rects.stories.tsx
  stories/bar/48_test_tooltip.tsx
  stories/utils/knobs.ts
Labels: :annotation, enhancement

#740 ci: add basic github checks
  github_checks_api.json
  package.json
  yarn.lock
Labels: :build, :ci, wip

#742 fix(axes): correctly remove only consecutive duplicated ticks
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-line-chart-multi-series-with-log-values-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/axis-stories-test-ts-axis-stories-should-hide-consecutive-duplicate-ticks-1-snap.png
  integration/tests/axis_stories.test.ts
  src/chart_types/xy_chart/utils/axis_utils.test.ts
  src/chart_types/xy_chart/utils/axis_utils.ts
  src/utils/commons.ts
  stories/axes/12_duplicate_ticks.tsx
Labels: :axis, bug

#746 build: update storybook to 5.3.19
  .storybook/webpack.config.js
  package.json
  yarn.lock
Labels: :build, dependencies

#745 build: update EUI to 27.0.0
  integration/tests/__image_snapshots__/legend-stories-test-ts-legend-stories-should-render-color-picker-on-mouse-click-1-snap.png
  package.json
  src/_eui_imports.scss
  yarn.lock
Labels: :build, dependencies

#750 feat(axis): formatting different for label vs tooltip and legend
  api/charts.api.md
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-axes-label-formatting-visually-looks-correct-1-snap.png
  package.json
  src/chart_types/xy_chart/renderer/canvas/axes/tick_label.ts
  src/chart_types/xy_chart/utils/axis_utils.ts
  src/chart_types/xy_chart/utils/specs.ts
  stories/axes/13_label_formatting.tsx
  stories/axes/axes.stories.tsx
Labels: :axis, enhancement

#754 docs: improve install instructions on readme
  README.md
Labels: :docs

#757 fix: custom domain with fallback ordinal scale
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-scales-x-scale-fallback-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/domains/x_domain.test.ts
  src/chart_types/xy_chart/domains/x_domain.ts
  stories/scales/6_x_scale_fallback.tsx
  stories/scales/scales.stories.tsx
Labels: :data, bug

#760 fix(axis): dual axis x positioning of bars
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-test-dual-y-axis-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/state/utils/utils.ts
  stories/bar/49_test_dual_axis.tsx
  stories/bar/bars.stories.tsx
Labels: :xy, bug, regression

#762 fix(axis): left axis sizing based on title padding
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-test-stacked-with-missing-values-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-with-4-axes-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-interactions-cursor-update-action-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-interactions-png-export-action-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-scales-remove-duplicate-axis-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-scales-specified-timezone-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-scales-timezone-configuration-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-scales-tooltip-in-local-timezone-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-scales-tooltip-in-utc-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-interactions-tooltip-sync-show-synced-tooltips-1-snap.png
  src/chart_types/xy_chart/utils/axis_utils.test.ts
  src/chart_types/xy_chart/utils/axis_utils.ts
Labels: :axis, bug, regression

#765 fix(axis): dual axis x positioning of bars (#760) [19.8.x]
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-test-dual-y-axis-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/state/utils/utils.ts
  stories/bar/49_test_dual_axis.tsx
  stories/bar/bars.stories.tsx
Labels: backport

#763 fix: update dep vulnerabilities, minimist and kind-of
  yarn.lock
Labels: :build, chore, security

#772 ci: fix browser-ie failure
  .github/workflows/smoke_tests.yaml
Labels: :ci

#774 fix(legend): fix color anchor, add action context, fix action padding
  api/charts.api.md
  integration/tests/__image_snapshots__/legend-stories-test-ts-legend-stories-should-render-color-picker-on-mouse-click-1-snap.png
  src/components/__snapshots__/chart.test.tsx.snap
  src/components/icons/icon.tsx
  src/components/legend/__snapshots__/legend.test.tsx.snap
  src/components/legend/_legend_item.scss
  src/components/legend/color.tsx
  src/components/legend/legend_item.tsx
  src/specs/settings.tsx
  src/state/selectors/get_legend_size.ts
  stories/legend/11_legend_actions.tsx
  stories/legend/9_color_picker.tsx
  stories/utils/knobs.ts
Labels: :legend
