Repository elastic/elastic-charts, pull requests merged in 2020-09, with the labels that each got.

#801 feat(brush): histogram brushing last values and rounding
  api/charts.api.md
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-interactions-brush-selection-tool-on-bar-chart-histogram-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts
  src/specs/settings.tsx
  stories/interactions/10_brush_selection_bar.tsx
  stories/interactions/10a_brush_selection_bar_hist.tsx
  stories/interactions/12_brush_time_hist.tsx
  stories/interactions/interactions.stories.tsx
Labels: :vislib

#805 fix(axis): misaligned axis with rotated histogram
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-axis-positions-with-histogram-bar-series-should-render-correct-axis-rotation-0-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-axis-positions-with-histogram-bar-series-should-render-correct-axis-rotation-180-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-axis-positions-with-histogram-bar-series-should-render-correct-axis-rotation-90-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-axis-positions-with-histogram-bar-series-should-render-correct-axis-rotation-negative-90-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-linear-enable-histogram-mode-is-true-rotation-180-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-linear-enable-histogram-mode-is-true-rotation-negative-90-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-linear-point-alignment-center-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-linear-point-alignment-end-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-linear-point-alignment-start-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-ordinal-enable-histogram-mode-is-false-has-histogram-bar-series-is-false-rotation-180-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-ordinal-enable-histogram-mode-is-false-has-histogram-bar-series-is-false-rotation-negative-90-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-ordinal-enable-histogram-mode-is-true-has-histogram-bar-series-is-true-rotation-180-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-test-histogram-mode-ordinal-enable-histogram-mode-is-true-has-histogram-bar-series-is-true-rotation-negative-90-1-snap.png
  integration/tests/bar_stories.test.ts
  src/chart_types/xy_chart/utils/axis_utils.test.ts
  src/chart_types/xy_chart/utils/axis_utils.ts
  src/mocks/scale/scale.ts
  src/scales/index.ts
  src/scales/scale_continuous.ts
Labels: :axis, :xy, bug

#806 build(deps): bump dot-prop from 3.0.0 to 5.2.0
  package.json
  yarn.lock
Labels: :build, dependencies

#807 build(deps): bump prismjs from 1.17.1 and 1.16.0 to 1.21.0
  package.json
  yarn.lock
Labels: :build, dependencies, security

#812 fix: remove unused redux dev middlewares
  package.json
  src/components/chart.tsx
  yarn.lock
Labels: :build, bug, dependencies

#813 feat: blind sorting option for vislib
  src/chart_types/xy_chart/state/selectors/compute_series_domains.ts
  src/chart_types/xy_chart/state/utils/utils.ts
  src/chart_types/xy_chart/utils/series.ts
Labels: :data, :specs, :vislib

#814 feat: order ordinal values by sum
  api/charts.api.md
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-order-bins-by-sum-visually-looks-correct-1-snap.png
  integration/tests/legend_stories.test.ts
  src/chart_types/xy_chart/domains/x_domain.test.ts
  src/chart_types/xy_chart/state/selectors/compute_series_domains.ts
  src/chart_types/xy_chart/state/utils/utils.ts
  src/chart_types/xy_chart/utils/series.test.ts
  src/chart_types/xy_chart/utils/series.ts
  src/specs/constants.ts
  src/specs/settings.tsx
  stories/bar/50_order_bins_by_sum.tsx
  stories/bar/bars.stories.tsx
Labels: :axis, :vislib, :xy, enhancement

#775 feat(series): add simple mark formatter
  .eslintrc.js
  api/charts.api.md
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-mixed-charts-mark-size-accessor-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-interactions-tooltip-formatting-should-use-custom-mark-formatters-1-snap.png
  integration/tests/interactions.test.ts
  src/chart_types/xy_chart/tooltip/tooltip.test.ts
  src/chart_types/xy_chart/tooltip/tooltip.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/components/tooltip/tooltip.tsx
  src/specs/settings.tsx
  stories/mixed/7_marks.tsx
Labels: :data, :tooltip, :xy

#817 fix: show crosshairs for external pointer events
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-interactions-cursor-update-action-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-interactions-tooltip-sync-show-synced-crosshairs-1-snap.png
  integration/tests/__image_snapshots__/interactions-test-ts-interactions-tooltip-sync-show-synced-tooltips-1-snap.png
  integration/tests/interactions.test.ts
  src/chart_types/xy_chart/renderer/dom/crosshair.tsx
  stories/interactions/16_cursor_update_action.tsx
  stories/utils/knobs.ts
Labels: :interactions, regression

#818 docs: custom tooltip example for partition charts
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-custom-tooltip-visually-looks-correct-1-snap.png
  stories/sunburst/32_custom_tooltip.tsx
  stories/sunburst/sunburst.stories.tsx
Labels: :docs

#821 refactor: decouple the brush component from XY chart
  src/chart_types/goal_chart/state/chart_state.tsx
  src/chart_types/partition_chart/state/chart_state.tsx
  src/chart_types/xy_chart/renderer/dom/_index.scss
  src/chart_types/xy_chart/state/chart_state.tsx
  src/components/_index.scss
  src/components/brush/_brush.scss
  src/components/brush/_index.scss
  src/components/brush/brush.tsx
  src/state/chart_state.ts
  src/state/selectors/get_internal_brush_area.ts
  src/state/selectors/get_internal_main_projection_area.ts
  src/state/selectors/get_internal_projection_container_area.ts
Labels: :interactions, enhancement

#820 fix: legend dark mode hover color
  integration/tests/__image_snapshots__/legend-stories-test-ts-legend-stories-should-render-color-picker-on-mouse-click-1-snap.png
  integration/tests/__image_snapshots__/legend-stories-test-ts-legend-stories-should-render-legend-action-on-mouse-hover-1-snap.png
  src/components/legend/_legend_item.scss
Labels: :legend, :styling, bug

#824 fix: line path with ordered xValues
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-line-chart-test-path-ordering-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/line-stories-test-ts-line-series-stories-line-paths-for-ordered-values-should-render-correct-line-path-non-stacked-1-snap.png
  integration/tests/__image_snapshots__/line-stories-test-ts-line-series-stories-line-paths-for-ordered-values-should-render-correct-line-path-stacked-1-snap.png
  integration/tests/line_stories.test.ts
  src/chart_types/xy_chart/utils/fill_series.ts
  src/chart_types/xy_chart/utils/series.ts
  stories/line/10_test_path_ordering.tsx
  stories/line/line.stories.tsx
Labels: :data, bug, regression

#829 fix(axis): style overrides not applied to axis dimensions
  integration/tests/__image_snapshots__/axis-stories-test-ts-axis-stories-should-render-correctly-rotated-ticks-1-snap.png
  integration/tests/axis_stories.test.ts
  src/chart_types/xy_chart/state/selectors/compute_axis_ticks_dimensions.ts
Labels: :axis, bug

#822 feat: expose datum as part of GeometryValue
  api/charts.api.md
  src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  src/chart_types/xy_chart/rendering/rendering.bands.test.ts
  src/chart_types/xy_chart/rendering/rendering.bars.test.ts
  src/chart_types/xy_chart/rendering/rendering.bubble.test.ts
  src/chart_types/xy_chart/rendering/rendering.lines.test.ts
  src/chart_types/xy_chart/rendering/rendering.test.ts
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/state/chart_state.interactions.test.ts
  src/chart_types/xy_chart/state/chart_state.test.ts
  src/chart_types/xy_chart/state/utils/utils.test.ts
  src/chart_types/xy_chart/tooltip/tooltip.test.ts
  src/chart_types/xy_chart/utils/interactions.test.ts
  src/mocks/geometries.ts
  src/utils/geometry.ts
  stories/interactions/1_bar_clicks.tsx
Labels: :interactions, :xy, enhancement
