Repository elastic/elastic-charts, pull requests merged in 2020-01, with the labels that each got.

#506 fix(specs): shows a chart message without series specified
  .playground/index.html
  .playground/playgroud.tsx
  src/components/chart.test.tsx
  src/components/chart.tsx
  src/components/chart_container.tsx
  src/state/selectors/is_initialized.ts
  src/state/utils.ts
Labels: enhancement

#510 feat: add domain fitting
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-axis-fit-domain-to-extent-in-y-axis-visually-looks-correct-1-snap.png
  package.json
  src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
  src/chart_types/xy_chart/crosshair/crosshair_utils.ordinal_snap.test.ts
  src/chart_types/xy_chart/domains/x_domain.test.ts
  src/chart_types/xy_chart/domains/y_domain.test.ts
  src/chart_types/xy_chart/domains/y_domain.ts
  src/chart_types/xy_chart/renderer/canvas/reactive_chart.tsx
  src/chart_types/xy_chart/renderer/canvas/utils/rendering_props_utils.test.ts
  src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  src/chart_types/xy_chart/rendering/rendering.bands.test.ts
  src/chart_types/xy_chart/rendering/rendering.bars.test.ts
  src/chart_types/xy_chart/rendering/rendering.lines.test.ts
  src/chart_types/xy_chart/rendering/rendering.test.ts
  src/chart_types/xy_chart/rendering/rendering.ts
  src/chart_types/xy_chart/state/chart_state.interactions.test.ts
  src/chart_types/xy_chart/state/chart_state.test.ts
  src/chart_types/xy_chart/state/chart_state.timescales.test.ts
  src/chart_types/xy_chart/state/chart_state.tooltip.test.ts
  src/chart_types/xy_chart/state/selectors/get_cursor_band.ts
  src/chart_types/xy_chart/state/selectors/get_specs.ts
  src/chart_types/xy_chart/state/selectors/get_tooltip_snap.ts
  src/chart_types/xy_chart/state/selectors/get_tooltip_type.ts
  src/chart_types/xy_chart/state/selectors/is_chart_empty.ts
  src/chart_types/xy_chart/state/selectors/is_histogram_mode_enabled.ts
  src/chart_types/xy_chart/state/utils.test.ts
  src/chart_types/xy_chart/utils/axis_utils.ts
  src/chart_types/xy_chart/utils/nonstacked_series_utils.test.ts
  src/chart_types/xy_chart/utils/series.test.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/chart_types/xy_chart/utils/stacked_percent_series_utils.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.test.ts
  src/components/chart_container.tsx
  src/components/chart_resizer.tsx
  src/components/legend/legend.test.tsx
  src/components/legend/legend.tsx
  src/specs/specs_parser.test.tsx
  src/specs/specs_parser.tsx
  src/state/spec_factory.ts
  src/utils/commons.test.ts
  src/utils/commons.ts
  src/utils/data_generators/data_generator.ts
  src/utils/data_samples/test_dataset.ts
  src/utils/domain.test.ts
  src/utils/domain.ts
  src/utils/ids.test.ts
  stories/annotations.tsx
  stories/area_chart.tsx
  stories/axis.tsx
  stories/bar_chart.tsx
  stories/grid.tsx
  stories/interactions.tsx
  stories/legend.tsx
  stories/mixed.tsx
  stories/rotations.tsx
  stories/scales.tsx
  stories/styling.tsx
  yarn.lock
Labels: :axis

#511 fix: add domain fitting for tsvb regression
  src/chart_types/xy_chart/domains/y_domain.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/utils/data_generators/data_generator.ts
  src/utils/domain.test.ts
  src/utils/domain.ts
Labels: backport, regression

#513 docs: add backport config and docs
  .backportrc.json
  CONTRIBUTING.md
  package.json
  yarn.lock
Labels: ci, dependencies, docs

#524 feat: text improvements
  .playground/playground.tsx
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-big-empty-pie-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-clockwise-no-special-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-counter-clockwise-special-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-donut-chart-with-fill-labels-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-full-zero-slice-pie-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-high-number-of-slice-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-linked-labels-only-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-no-labels-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-pie-chart-labels-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-pie-chart-with-fill-labels-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-simple-pie-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-single-small-slice-pie-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-single-very-small-slice-pie-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-some-zero-value-slice-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-sunburst-three-layers-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-sunburst-two-layers-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-two-slices-pie-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-value-formatted-pie-chart-2-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-value-formatted-pie-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-very-large-small-pie-chart-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-treemap-custom-style-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-treemap-mid-two-layers-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-treemap-multi-color-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-treemap-one-layer-2-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-treemap-two-layers-stress-test-visually-looks-correct-1-snap.png
  src/chart_types/partition_chart/layout/config/config.ts
  src/chart_types/partition_chart/layout/types/config_types.ts
  src/chart_types/partition_chart/layout/types/types.ts
  src/chart_types/partition_chart/layout/types/viewmodel_types.ts
  src/chart_types/partition_chart/layout/utils/group_by_rollup.ts
  src/chart_types/partition_chart/layout/utils/measure.ts
  src/chart_types/partition_chart/layout/utils/sunburst.ts
  src/chart_types/partition_chart/layout/viewmodel/fill_text_layout.ts
  src/chart_types/partition_chart/layout/viewmodel/link_text_layout.ts
  src/chart_types/partition_chart/layout/viewmodel/viewmodel.ts
  src/chart_types/partition_chart/renderer/canvas/canvas_renderers.ts
  src/chart_types/partition_chart/specs/index.ts
  src/index.ts
  stories/sunburst.tsx
  stories/treemap.tsx
  stories/utils/utils.ts
Labels: enhancement

#529 test: add polyfills for IE11 testing
  .playground/index.tsx
  .playground/tsconfig.json
  package.json
  yarn.lock
Labels: chore

#525 feat(listeners): add seriesIdentifiers to element listeners
  src/chart_types/xy_chart/state/chart_state.interactions.test.ts
  src/chart_types/xy_chart/state/selectors/on_element_click_caller.ts
  src/chart_types/xy_chart/state/selectors/on_element_over_caller.ts
  src/specs/settings.tsx
Labels: :interactions, enhancement

#528 fix(brush): rotate brush on rotated charts
  .playground/index.html
  .playground/playground.tsx
  src/chart_types/xy_chart/renderer/dom/brush.tsx
  src/chart_types/xy_chart/state/chart_state.interactions.test.ts
  src/chart_types/xy_chart/state/chart_state.test.ts
  src/chart_types/xy_chart/state/selectors/get_brush_area.ts
  src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts
  src/state/reducers/interactions.ts
  stories/interactions.tsx
Labels: :interactions, bug
