Repository elastic/elastic-charts, pull requests merged in 2020-11, with the labels that each got.

#892 docs: add randomness toggle on fit stacked series story
  stories/mixed/6_fitting_stacked.tsx
Labels: :docs

#631 docs: add more knobs to gauge stories
  stories/goal/2_gauge_with_target.tsx
Labels: :docs

#900 fix: render orphan data points on lines and areas
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-with-log-y-axis-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-line-chart-test-orphan-data-points-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/area-stories-test-ts-area-series-stories-area-with-orphan-data-points-render-correctly-fit-function-1-snap.png
  integration/tests/__image_snapshots__/area-stories-test-ts-area-series-stories-non-stacked-linear-area-with-discontinuous-data-points-no-fit-function-1-snap.png
  integration/tests/area_stories.test.ts
  src/chart_types/xy_chart/renderer/canvas/areas.ts
  src/chart_types/xy_chart/renderer/canvas/bars.ts
  src/chart_types/xy_chart/renderer/canvas/bubbles.ts
  src/chart_types/xy_chart/renderer/canvas/lines.ts
  src/chart_types/xy_chart/rendering/area.ts
  src/chart_types/xy_chart/rendering/line.ts
  src/chart_types/xy_chart/rendering/points.ts
  src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  src/chart_types/xy_chart/rendering/rendering.bands.test.ts
  src/chart_types/xy_chart/rendering/utils.ts
  src/mocks/geometries.ts
  src/mocks/series/utils.ts
  src/utils/geometry.ts
  stories/line/12_orphan_data_points.tsx
  stories/line/line.stories.tsx
Labels: :chart, :xy, enhancement

#903 fix(area_charts): correctly represent baseline with negative data points [23.x]
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-with-log-y-axis-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-with-negative-and-positive-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-with-negative-band-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-with-negative-values-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/area-stories-test-ts-area-series-stories-negative-log-areas-snows-negative-values-with-log-scale-1-snap.png
  integration/tests/__image_snapshots__/area-stories-test-ts-area-series-stories-negative-log-areas-snows-only-negative-values-when-hiding-positive-one-1-snap.png
  integration/tests/__image_snapshots__/area-stories-test-ts-area-series-stories-negative-log-areas-snows-only-positive-domain-mixed-polarity-domain-1-snap.png
  integration/tests/__image_snapshots__/area-stories-test-ts-area-series-stories-negative-log-areas-snows-only-positive-values-when-hiding-negative-one-1-snap.png
  integration/tests/area_stories.test.ts
  src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  src/chart_types/xy_chart/rendering/rendering.bubble.test.ts
  src/chart_types/xy_chart/rendering/rendering.lines.test.ts
  src/chart_types/xy_chart/rendering/rendering.ts
  src/mocks/series/utils.ts
  src/scales/constants.ts
  src/scales/scale_continuous.ts
  stories/area/17_negative.tsx
  stories/area/18_negative_positive.tsx
  stories/area/19_negative_band.tsx
  stories/area/area.stories.tsx
Labels: backport

#899 feat: allow clearing colors from memory
  api/charts.api.md
  integration/tests/__image_snapshots__/legend-stories-test-ts-legend-stories-should-render-color-picker-on-mouse-click-1-snap.png
  src/chart_types/xy_chart/utils/series.ts
  src/components/legend/legend_item.tsx
  src/specs/settings.tsx
  src/state/actions/colors.ts
  src/state/chart_state.ts
  stories/legend/9_color_picker.tsx
Labels: :interactions, :legend, enhancement

#901 fix: specs swaps correctly reflected in state
  src/state/chart_state.ts
  src/state/spec_factory.test.tsx
  src/state/spec_factory.ts
Labels: :specs, bug

#904 ci: disable IE workflow
  .github/workflows/smoke_tests.yaml.disabled
Labels: :ci

#912 feat: merge series domain with the domain of another group
  api/charts.api.md
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-dual-axis-same-y-domain-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-specify-domain-from-different-group-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-stacked-only-grouped-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-different-group-id-render-different-axis-scale-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-different-group-id-render-the-same-domain-with-use-default-group-domain-1-snap.png
  integration/tests/bar_stories.test.ts
  src/chart_types/xy_chart/domains/y_domain.ts
  src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
  src/chart_types/xy_chart/state/utils/spec.ts
  src/chart_types/xy_chart/state/utils/utils.ts
  src/chart_types/xy_chart/utils/specs.ts
  stories/bar/52_multi_group_same_domain.tsx
  stories/bar/53_use_domain_from_different_groupid.tsx
  stories/bar/bars.stories.tsx
Labels: :data, bug, enhancement, regression

#913 feat: add projection click listener
  api/charts.api.md
  src/chart_types/xy_chart/state/chart_state.tsx
  src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
  src/chart_types/xy_chart/state/selectors/get_projected_scaled_values.ts
  src/chart_types/xy_chart/state/selectors/on_click_caller.ts
  src/specs/settings.tsx
  stories/interactions/1_bar_clicks.tsx
Labels: :interactions, :xy, enhancement

#926 fix(highlighter): show default highlighted radius with hidden dots
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-line-chart-line-with-mark-accessor-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/line-stories-test-ts-line-series-stories-line-with-mark-accessor-with-hidden-points-default-point-highlighter-size-1-snap.png
  integration/tests/line_stories.test.ts
  src/chart_types/xy_chart/state/utils/utils.ts
  stories/line/13_line_mark_accessor.tsx
  stories/line/line.stories.tsx
Labels: :xy, bug
