Repository elastic/elastic-charts, pull requests merged in 2020-04, with the labels that each got.

#618 fix: stack as percentage with 0 or null values
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-stacked-percentage-with-zeros-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.ts
  stories/area/8_stacked_percentage_zeros.tsx
  stories/area/area.stories.tsx
Labels: :data, bug, regression

#619 fix: stack as percentage with 0 or null values (#618) [18.1.x]
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-stacked-percentage-with-zeros-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.ts
  stories/area/8_stacked_percentage_zeros.tsx
  stories/area/area.stories.tsx
Labels: backport

#622 fix: stacked percentage with zero values
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-area-chart-stacked-percentage-with-zeros-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.test.ts
  src/chart_types/xy_chart/utils/stacked_series_utils.ts
  stories/area/8_stacked_percentage_zeros.tsx
Labels: :data, bug

#636 fix(treemap): align onElementClick parameters to sunburst
  .playground/index.html
  .playground/playground.tsx
  src/chart_types/partition_chart/layout/viewmodel/viewmodel.ts
  src/chart_types/partition_chart/state/selectors/picked_shapes.test.ts
  src/chart_types/partition_chart/state/selectors/picked_shapes.ts
  src/mocks/specs/specs.ts
  stories/interactions/4_sunburst_slice_clicks.tsx
Labels: :interactions, :partition, bug

#645 fix: type issue pulling from src/index
  .eslintignore
  .eslintrc.js
  package.json
  src/chart_types/xy_chart/utils/specs.ts
  src/mocks/series/series_identifiers.ts
  src/mocks/utils.ts
  src/specs/specs_parser.test.tsx
  tsconfig.lib-check.json
  tsconfig.lib.json
  yarn.lock
Labels: :build, bug

#649 fix: tickFormat called on mark value
  src/chart_types/xy_chart/tooltip/tooltip.test.ts
  src/chart_types/xy_chart/tooltip/tooltip.ts
Labels: :tooltip, bug

#648 feat: shift click legend items & partition legend hover
  src/chart_types/xy_chart/legend/legend.test.ts
  src/chart_types/xy_chart/legend/legend.ts
  src/commons/legend.ts
  src/components/legend/__snapshots__/legend.test.tsx.snap
  src/components/legend/_legend_item.scss
  src/components/legend/color.tsx
  src/components/legend/label.tsx
  src/components/legend/legend_item.tsx
  src/state/actions/legend.ts
  src/state/chart_state.ts
  src/state/reducers/interactions.ts
Labels: :legend, enhancement

#653 test: improve VRT developer experience
  .ci/run.sh
  integration/defaults.js
  integration/helpers.ts
  integration/jest_puppeteer.config.js
  integration/tests/all.test.ts
  package.json
  wiki/testing.md
Labels: enhancement, visual testing

#657 fix: empty charts causing errors
  .playground/playground.tsx
  src/chart_types/goal_chart/renderer/canvas/connected_component.tsx
  src/chart_types/goal_chart/state/chart_state.tsx
  src/chart_types/partition_chart/renderer/canvas/partition.tsx
  src/chart_types/partition_chart/renderer/dom/highlighter_hover.tsx
  src/chart_types/partition_chart/renderer/dom/highlighter_legend.tsx
  src/chart_types/partition_chart/state/chart_state.tsx
  src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
  src/chart_types/xy_chart/renderer/dom/annotation_tooltips.tsx
  src/chart_types/xy_chart/renderer/dom/brush.tsx
  src/chart_types/xy_chart/renderer/dom/crosshair.tsx
  src/chart_types/xy_chart/renderer/dom/highlighter.tsx
  src/chart_types/xy_chart/state/chart_state.tsx
  src/components/chart.tsx
  src/components/chart_container.tsx
  src/components/legend/legend.tsx
  src/components/tooltip/tooltip_portal.tsx
  src/state/chart_state.ts
  src/state/selectors/get_internal_is_intialized.ts
Labels: :specs, bug, regression
