Repository elastic/elastic-charts, pull requests merged in 2020-12, with the labels that each got.

#934 fix: point highlight based on geom position and transform
  src/chart_types/xy_chart/rendering/utils.ts
  src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.test.ts
Labels: :interactions, :xy, bug, regression

#933 feat: improved domain error handling
  src/chart_types/xy_chart/domains/x_domain.test.ts
  src/chart_types/xy_chart/domains/x_domain.ts
  src/chart_types/xy_chart/domains/y_domain.test.ts
  src/chart_types/xy_chart/domains/y_domain.ts
Labels: :data

#943 feat: allow use of functions for y, y0, split and stack accessors
  api/charts.api.md
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-bar-chart-functional-accessors-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-functional-accessors-functional-accessors-with-field-name-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-functional-accessors-functional-accessors-with-field-name-with-tooltip-1-snap.png
  integration/tests/__image_snapshots__/bar-stories-test-ts-bar-series-stories-functional-accessors-y-1-accessors-and-y-0-accessors-1-snap.png
  integration/tests/bar_stories.test.ts
  src/chart_types/xy_chart/utils/__snapshots__/series.test.ts.snap
  src/chart_types/xy_chart/utils/series.test.ts
  src/chart_types/xy_chart/utils/series.ts
  src/chart_types/xy_chart/utils/specs.ts
  src/utils/accessor.ts
  stories/bar/33_band_bar.tsx
  stories/bar/54_functional_accessors.tsx
  stories/bar/bars.stories.tsx
Labels: :data, :xy, enhancement

#945 docs: fix color picker clearing logic
  stories/legend/9_color_picker.tsx
Labels: :docs

#952 fix(legend): disable focus and keyboard navigation for legend in partition ch…
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-sunburst-sunburst-with-three-layers-visually-looks-correct-1-snap.png
  src/components/legend/label.tsx
  src/components/legend/legend_item.tsx
Labels: :legend, :partition, bug
