Repository elastic/elastic-charts, pull requests merged in 2021-05, with the labels that each got.

#1173 fix(flamegraph): render nodeLabel formatted text into the nodes
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-flame-alpha-cpu-profile-flame-chart-visually-looks-correct-1-snap.png
  src/chart_types/partition_chart/renderer/canvas/canvas_linear_renderers.ts
  stories/icicle/03_cpu_profile_flame.tsx
Labels: :flamegraph

#1164 build: enable linking charts library to kibana
  .eslintrc.js
  package.json
  packages/eslint-plugin-elastic-charts/package.json
  packages/link_kibana/index.js
  packages/link_kibana/main.js
  packages/link_kibana/package.json
  packages/link_kibana/process_utils.js
  packages/link_kibana/replace_modules.js
  packages/link_kibana/utils.js
  packages/link_kibana/yarn.lock
  tsconfig.lib-nocomments.json
  tsconfig.lib.json
  yarn.lock
Labels: :build

#1167 fix: annotation tooltip display when remounting specs
  src/chart_types/xy_chart/state/selectors/get_annotation_tooltip_state.ts
Labels: :annotation, bug

#1146 refactor: remove `yScaleToDataExtent` option
  api/charts.api.md
  docs/0-Intro/1-Overview.mdx
  docs/1-Typesofchart/3-Stacked.mdx
  docs/2-ChartPropTables/13-AreaProps.md
  docs/2-ChartPropTables/14-LineProps.md
  src/chart_types/xy_chart/domains/x_domain.test.ts
  src/chart_types/xy_chart/domains/y_domain.ts
  src/chart_types/xy_chart/specs/area_series.tsx
  src/chart_types/xy_chart/specs/bar_series.tsx
  src/chart_types/xy_chart/specs/bubble_series.tsx
  src/chart_types/xy_chart/specs/histogram_bar_series.tsx
  src/chart_types/xy_chart/specs/line_series.tsx
  src/chart_types/xy_chart/utils/specs.ts
  src/components/__snapshots__/chart.test.tsx.snap
  stories/bar/32_scale_to_extent.tsx
Labels: :data, breaking change
