Repository elastic/elastic-charts, pull requests merged in 2021-02, with the labels that each got.

#1003 fix: external tooltip legend extra value sync (#993) [24.4.x]
  src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
Labels: backport

#1005 fix: missing exported types
  api/charts.api.md
  src/chart_types/heatmap/specs/heatmap.ts
  src/chart_types/heatmap/specs/index.ts
  src/chart_types/partition_chart/layout/types/viewmodel_types.ts
  src/chart_types/partition_chart/layout/utils/group_by_rollup.ts
  src/index.ts
Labels: :build

#1018 build: update semantic-release deps
  package.json
  yarn.lock
Labels: :build

#995 feat(partition): drilldown
  .playground/playground.tsx
  api/charts.api.md
  src/chart_types/partition_chart/layout/config.ts
  src/chart_types/partition_chart/layout/types/config_types.ts
  src/chart_types/partition_chart/layout/utils/group_by_rollup.ts
  src/chart_types/partition_chart/layout/viewmodel/hierarchy_of_arrays.test.ts
  src/chart_types/partition_chart/layout/viewmodel/hierarchy_of_arrays.ts
  src/chart_types/partition_chart/state/selectors/tree.ts
  src/state/chart_state.ts
  src/state/reducers/interactions.ts
  stories/icicle/01_unix_icicle.tsx
  stories/icicle/02_unix_flame.tsx
Labels: :partition, discuss, enhancement

#1024 docs: fix: line color function
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-stylings-custom-series-colors-via-accessor-function-visually-looks-correct-1-snap.png
  stories/stylings/9_custom_series_colors_function.tsx
Labels: :docs

#1023 feat: sort values in actions by closest to cursor
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-interactions-line-point-clicks-and-hovers-visually-looks-correct-1-snap.png
  src/chart_types/xy_chart/state/selectors/get_elements_at_cursor_pos.test.ts
  src/chart_types/xy_chart/state/selectors/get_elements_at_cursor_pos.ts
  src/chart_types/xy_chart/state/utils/common.test.ts
  src/chart_types/xy_chart/state/utils/common.ts
  src/utils/common.ts
  stories/interactions/3_line_point_clicks.tsx
Labels: :interactions, enhancement

#1019 fix(legend): width with scroll bar
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-rotations-with-ordinal-axis-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-treemap-mid-two-layers-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/legend-stories-test-ts-legend-stories-should-adjust-legend-width-for-scrollbar-1-snap.png
  integration/tests/legend_stories.test.ts
  src/components/legend/_legend.scss
  src/state/selectors/get_legend_size.ts
Labels: :legend, bug
