Repository elastic/elastic-charts, pull requests merged in 2022-11, with the labels that each got.

#1856 feat(xy): zoom pan numerical raster and other improvements
  e2e/screenshots/all.test.ts-snapshots/baselines/timeslip-alpha/timeslip-prototype-chrome-linux.png
  e2e/screenshots/axis_stories.test.ts-snapshots/axis-stories/renders-multilayer-time-axis-with-a-single-point-and-a-degenerate-zero-width-domain-chrome-linux.png
  e2e/screenshots/axis_stories.test.ts-snapshots/axis-stories/uses-proper-english-ending-at-a-daily-resolution-30th-14th-chrome-linux.png
  packages/charts/src/chart_types/partition_chart/layout/utils/legend.ts
  packages/charts/src/chart_types/timeslip/projections/axis_model.ts
  packages/charts/src/chart_types/timeslip/projections/domain_tween.ts
  packages/charts/src/chart_types/timeslip/projections/scale.ts
  packages/charts/src/chart_types/timeslip/projections/zoom_pan.ts
  packages/charts/src/chart_types/timeslip/timeslip/config.ts
  packages/charts/src/chart_types/timeslip/timeslip/data_fetch.ts
  packages/charts/src/chart_types/timeslip/timeslip/render/annotations/chart_title.ts
  packages/charts/src/chart_types/timeslip/timeslip/render/annotations/time_extent.ts
  packages/charts/src/chart_types/timeslip/timeslip/render/annotations/time_unit.ts
  packages/charts/src/chart_types/timeslip/timeslip/render/cartesian.ts
  packages/charts/src/chart_types/timeslip/timeslip/render/column.ts
  packages/charts/src/chart_types/timeslip/timeslip/render/glyphs/bar.ts
  packages/charts/src/chart_types/timeslip/timeslip/render/glyphs/boxplot.ts
  packages/charts/src/chart_types/timeslip/timeslip/render/raster.ts
  packages/charts/src/chart_types/timeslip/timeslip/timeslip_render.ts
  packages/charts/src/chart_types/timeslip/timeslip/utils/dom.ts
  packages/charts/src/chart_types/timeslip/timeslip_api.ts
  packages/charts/src/chart_types/timeslip/timeslip_chart.tsx
  packages/charts/src/chart_types/timeslip/utils/animation.ts
  packages/charts/src/chart_types/timeslip/utils/dom.ts
  packages/charts/src/chart_types/timeslip/utils/math.ts
  packages/charts/src/chart_types/timeslip/utils/multitouch.ts
  packages/charts/src/chart_types/xy_chart/axes/timeslip/continuous_time_rasters.ts
  packages/charts/src/chart_types/xy_chart/axes/timeslip/locale_translations.ts
  packages/charts/src/chart_types/xy_chart/axes/timeslip/multilayer_ticks.ts
  packages/charts/src/chart_types/xy_chart/axes/timeslip/numerical_rasters.ts
  packages/charts/src/common/iterables.ts
  playground/playground.tsx
  storybook/stories/bar/44_test_single_histogram.story.tsx
  storybook/stories/timeslip/01_timeslip.story.tsx
Labels: enhancement, :axis, :xy, :refactor

#1860 feat(flame): node size and position tweening
  packages/charts/src/chart_types/flame_chart/flame_api.ts
  packages/charts/src/chart_types/flame_chart/flame_chart.tsx
  packages/charts/src/chart_types/flame_chart/render/draw_a_frame.ts
  packages/charts/src/chart_types/flame_chart/render/draw_webgl.ts
  packages/charts/src/chart_types/flame_chart/shaders.ts
  playground/playground.tsx
  storybook/stories/icicle/04_cpu_profile_gl_flame.story.tsx
Labels: enhancement, :interactions, :flamegraph

#1866 fix(heatmap): cursor visible out of cell bounds
  e2e/screenshots/heatmap_stories.test.ts-snapshots/heatmap-stories/should-not-have-brush-tool-extend-into-axes-chrome-linux.png
  e2e/screenshots/heatmap_stories.test.ts-snapshots/heatmap-stories/theme-dark/should-render-correct-brush-area-chrome-linux.png
  e2e/screenshots/heatmap_stories.test.ts-snapshots/heatmap-stories/theme-eui-dark/should-render-correct-brush-area-chrome-linux.png
  e2e/screenshots/heatmap_stories.test.ts-snapshots/heatmap-stories/theme-eui-light/should-render-correct-brush-area-chrome-linux.png
  e2e/screenshots/heatmap_stories.test.ts-snapshots/heatmap-stories/theme-light/should-render-correct-brush-area-chrome-linux.png
  packages/charts/src/chart_types/heatmap/state/selectors/get_cursor_band.ts
  packages/charts/src/chart_types/heatmap/state/selectors/get_cursor_pointer.ts
  packages/charts/src/chart_types/heatmap/state/selectors/picked_shapes.ts
Labels: :interactions, :heatmap

#1869 fix: workaround firefox amd macbook regression webgl_gl_VertexID_Offset
  packages/charts/src/common/kingly.ts
Labels: :flamegraph

#1870 fix: workaround firefox amd macbook regression webgl_gl_VertexID_Offset (#1869) [50.2.x]
  packages/charts/src/common/kingly.ts
Labels: backport

#1880 docs: fix emotion/css build warning
  package.json
  storybook/package.json
  yarn.lock
Labels: :docs

#1883 fix(xy): cursor while dragging with no brushing
  packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
Labels: :interactions, :xy

#1886 fix(tooltip): check if scroll event target is null
  packages/charts/src/components/tooltip/tooltip.tsx
Labels: bug, :tooltip, :all
