Repository elastic/elastic-charts, pull requests merged in 2022-02, with the labels that each got.

#1572 ci(playwright): e2e framework setup
  .eslintignore
  .eslintrc.js
  .gitignore
  .nvmrc
  e2e-server/.firebaserc
  e2e-server/.gitignore
  e2e-server/firebase.json
  e2e-server/scripts/compile_vrt_page.sh
  e2e-server/scripts/extract_examples.sh
  e2e-server/scripts/start.sh
  e2e-server/server/generate/extract_examples.js
  e2e-server/server/generate/vrt_page_template.js
  e2e-server/server/webpack.config.js
  e2e-server/tsconfig.json
  e2e/.gitignore
  e2e/constants.ts
  e2e/e2e_config.ts
  e2e/helpers.ts
  e2e/package.json
  e2e/page_objects/common.ts
  e2e/playwright.config.ts
  e2e/screenshots/.gitignore
  e2e/screenshots/get_new_mappings.ts
  e2e/screenshots/mappings.json
  e2e/screenshots/missing.json
  e2e/screenshots/move_screenshots.ts
  e2e/screenshots/new_mappings.json
  e2e/scripts/clean.sh
  e2e/scripts/start.sh
  e2e/scripts/test.sh
  e2e/tests/all.test.ts
  e2e/tests/annotations_stories.test.ts
  e2e/tests/area_stories.test.ts
  e2e/tests/axis_stories.test.ts
  e2e/tests/bar_stories.test.ts
  e2e/tests/dark_mode.test.ts
  e2e/tests/goal_stories.test.ts
  e2e/tests/grid_stories.test.ts
  e2e/tests/heatmap_stories.test.ts
  e2e/tests/interactions.test.ts
  e2e/tests/legend_stories.test.ts
  e2e/tests/line_stories.test.ts
  e2e/tests/mixed_stories.test.ts
  e2e/tests/partition_stories.test.ts
  e2e/tests/scales_stories.test.ts
  e2e/tests/styles.test.ts
  e2e/tests/stylings_stories.test.ts
  e2e/tests/test_cases_stories.test.ts
  e2e/tests/timezone.test.ts
  e2e/tests/waffle_stories.test.ts
  e2e/tests/wordcloud_stories.test.ts
  e2e/yarn.lock
  integration/page_objects/common.ts
  lerna.json
  package.json
  packages/charts/src/chart_types/heatmap/specs/heatmap.ts
  storybook/package.json
  storybook/webpack.config.js
  tsconfig.json
Labels: visual testing

#1595 ci: removing FOSSA license scanner
  .ci/jobs/elastic+elastic-charts+pr-license-scan.yml
  .ci/license_scan.sh
  .fossa.yml
Labels: dependencies, :ci

#1574 fix: expose Predicate enum
  packages/charts/api/charts.api.md
  packages/charts/src/index.ts
Labels: typings

#1597 fix(xy): dataIndex keep original data order on small multiples
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-small-multiples-alpha-sorting-visually-looks-correct-1-snap.png
  packages/charts/src/common/predicate.ts
  storybook/stories/small_multiples/1_grid.story.tsx
  storybook/stories/small_multiples/8_sorting.story.tsx
  storybook/stories/small_multiples/small_multiples.stories.tsx
Labels: :data, :xy, :small multiples

#1514 feat(heatmap): allow rotation of x axis labels
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-heatmap-alpha-basic-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-heatmap-alpha-categorical-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-heatmap-alpha-label-rotation-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-heatmap-alpha-theming-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-heatmap-alpha-time-snap-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-heatmap-alpha-time-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-rotate-categorical-axis-labels-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-rotate-time-axis-labels-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-should-maximize-the-label-font-size-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-should-maximize-the-label-with-an-unique-font-size-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-should-not-have-brush-tool-extend-into-axes-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-should-show-x-and-y-axis-titles-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-theme-dark-should-render-basic-heatmap-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-theme-dark-should-render-correct-brush-area-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-theme-eui-dark-should-render-basic-heatmap-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-theme-eui-dark-should-render-correct-brush-area-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-theme-eui-light-should-render-basic-heatmap-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-theme-eui-light-should-render-correct-brush-area-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-theme-light-should-render-basic-heatmap-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-theme-light-should-render-correct-brush-area-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-time-snap-with-dataset-2-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-time-snap-with-dataset-3-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-time-snap-with-dataset-4-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-time-snap-with-dataset-5-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-time-snap-with-dataset-6-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-time-snap-with-dataset-7-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-time-snap-with-dataset-8-1-snap.png
  integration/tests/__image_snapshots__/heatmap-stories-test-ts-heatmap-stories-time-snap-with-dataset-9-1-snap.png
  integration/tests/heatmap_stories.test.ts
  packages/charts/api/charts.api.md
  packages/charts/src/chart_types/heatmap/layout/types/viewmodel_types.ts
  packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
  packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
  packages/charts/src/chart_types/heatmap/renderer/canvas/connected_component.tsx
  packages/charts/src/chart_types/heatmap/state/selectors/compute_chart_dimensions.ts
  packages/charts/src/chart_types/heatmap/state/selectors/get_x_axis_right_overflow.ts
  packages/charts/src/common/math.ts
  packages/charts/src/common/vectors.ts
  packages/charts/src/scales/scale_continuous.ts
  packages/charts/src/solvers/screenspace_marker_scale_compressor.ts
  packages/charts/src/state/selectors/get_chart_theme.ts
  packages/charts/src/utils/common.ts
  packages/charts/src/utils/data_samples/test_dataset_heatmap.ts
  packages/charts/src/utils/themes/dark_theme.ts
  packages/charts/src/utils/themes/light_theme.ts
  packages/charts/src/utils/themes/theme.ts
  storybook/stories/heatmap/2_categorical.story.tsx
  storybook/stories/heatmap/6_label_rotation.story.tsx
  storybook/stories/heatmap/heatmap.stories.tsx
  storybook/stories/test_cases/9_heatmap_axis_labels.story.tsx
  storybook/stories/test_cases/test_cases.stories.tsx
Labels: enhancement, breaking change, :heatmap
