Repository elastic/elastic-charts, pull requests merged in 2022-06, with the labels that each got.

#1694 feat(flame): pulsate node on click focus and search hit focus
  packages/charts/src/chart_types/flame_chart/flame_chart.tsx
  packages/charts/src/chart_types/flame_chart/render/draw_a_frame.ts
  packages/charts/src/chart_types/flame_chart/render/draw_webgl.ts
  packages/charts/src/chart_types/flame_chart/render/ensure_webgl.ts
  packages/charts/src/chart_types/flame_chart/shaders.ts
Labels: enhancement, :flamegraph

#1674 fix(bubble): tooltip visibility on hover
  packages/charts/src/chart_types/xy_chart/renderer/canvas/renderers.ts
  packages/charts/src/chart_types/xy_chart/rendering/points.ts
  packages/charts/src/chart_types/xy_chart/rendering/rendering.bubble.test.ts
  packages/charts/src/chart_types/xy_chart/utils/indexed_geometry_spatial_map.ts
  packages/charts/src/renderers/canvas/index.ts
Labels: bug, :data, :xy

#1695 fix(flame): cross browser issues
  packages/charts/src/chart_types/flame_chart/flame_chart.tsx
  packages/charts/src/chart_types/flame_chart/shaders.ts
  packages/charts/src/common/kingly.ts
  storybook/stories/icicle/04_cpu_profile_gl_flame.story.tsx
Labels: :flamegraph

#1697 feat(flame): keyboard shortcuts for the text field
  packages/charts/src/chart_types/flame_chart/flame_chart.tsx
Labels: enhancement, :interactions, :accessibility, :flamegraph

#1699 chore: remove deprecated `link_kibana` tool
  .eslintrc.js
  package.json
  packages/link_kibana/index.js
  packages/link_kibana/main.js
  packages/link_kibana/package.json
  packages/link_kibana/process_utils.js
  packages/link_kibana/replace_modules.js
  packages/link_kibana/utils.js
  packages/link_kibana/yarn.lock
  yarn.lock
Labels: chore, :build

#1693 fix(annotations): animated fade trigger
  .gitignore
  integration/tests/__image_snapshots__/annotations-stories-test-ts-annotations-stories-outside-annotations-should-show-tooltip-on-hover-x-domain-1-snap.png
  integration/tests/__image_snapshots__/annotations-stories-test-ts-annotations-stories-outside-annotations-should-show-tooltip-on-hover-y-domain-1-snap.png
  packages/charts/api/charts.api.md
  packages/charts/src/chart_types/flame_chart/flame_api.ts
  packages/charts/src/chart_types/partition_chart/layout/types/viewmodel_types.ts
  packages/charts/src/chart_types/partition_chart/specs/index.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/annotations/index.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/annotations/lines.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/annotations/rect.ts
  packages/charts/src/chart_types/xy_chart/renderer/common/utils.ts
  packages/charts/src/chart_types/xy_chart/renderer/dom/annotations/annotations.tsx
  packages/charts/src/chart_types/xy_chart/renderer/dom/annotations/line_marker.tsx
  packages/charts/src/chart_types/xy_chart/state/selectors/get_annotation_tooltip_state.ts
  packages/charts/src/chart_types/xy_chart/utils/specs.ts
  packages/charts/src/common/animation.ts
  packages/charts/src/index.ts
  packages/charts/src/utils/themes/merge_utils.ts
  packages/charts/src/utils/themes/theme.test.ts
  packages/charts/src/utils/themes/theme.ts
  storybook/stories/annotations/rects/4_styling.story.tsx
Labels: bug, :interactions, :annotation, :xy, breaking change

#1658 feat(metric): Metric visualization
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-metric-alpha-basic-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-metric-alpha-grid-visually-looks-correct-1-snap.png
  integration/tests/__image_snapshots__/metric-stories-test-ts-metric-should-render-horizontal-progress-bar-1-snap.png
  integration/tests/__image_snapshots__/metric-stories-test-ts-metric-should-render-horizontal-progress-bar-in-dark-mode-1-snap.png
  integration/tests/__image_snapshots__/metric-stories-test-ts-metric-should-render-no-progress-bar-1-snap.png
  integration/tests/__image_snapshots__/metric-stories-test-ts-metric-should-render-no-progress-bar-in-dark-mode-1-snap.png
  integration/tests/__image_snapshots__/metric-stories-test-ts-metric-should-render-vertical-progress-bar-in-dark-mode-1-snap.png
  integration/tests/metric_stories.test.ts
  packages/charts/api/charts.api.md
  packages/charts/src/chart_types/index.ts
  packages/charts/src/chart_types/metric/renderer/_index.scss
  packages/charts/src/chart_types/metric/renderer/dom/_progress.scss
  packages/charts/src/chart_types/metric/renderer/dom/_sparkline.scss
  packages/charts/src/chart_types/metric/renderer/dom/_text.scss
  packages/charts/src/chart_types/metric/renderer/dom/index.tsx
  packages/charts/src/chart_types/metric/renderer/dom/progress.tsx
  packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
  packages/charts/src/chart_types/metric/renderer/dom/text.tsx
  packages/charts/src/chart_types/metric/specs/index.ts
  packages/charts/src/chart_types/metric/state/chart_state.tsx
  packages/charts/src/chart_types/metric/state/selectors/chart_size.ts
  packages/charts/src/chart_types/metric/state/selectors/data.ts
  packages/charts/src/chart_types/specs.ts
  packages/charts/src/common/color_library_wrappers.ts
  packages/charts/src/components/_index.scss
  packages/charts/src/geoms/path.ts
  packages/charts/src/state/chart_state.ts
  packages/charts/src/state/selectors/get_specs_by_type.ts
  packages/charts/src/utils/themes/dark_theme.ts
  packages/charts/src/utils/themes/light_theme.ts
  packages/charts/src/utils/themes/theme.ts
  storybook/stories/metric/1_basic.story.tsx
  storybook/stories/metric/2_grid.story.tsx
  storybook/stories/metric/metric.stories.tsx
Labels: :new chart type, :theme

#1709 fix(flame): no focus border
  packages/charts/src/chart_types/flame_chart/flame_chart.tsx
  storybook/stories/wordcloud/1_wordcloud.story.tsx
Labels: :interactions, :flamegraph

#1710 fix: return always a full projection in multilayerAxisEntry
  packages/charts/src/chart_types/xy_chart/axes/timeslip/multilayer_ticks.ts
  storybook/stories/area/21_with_time_timeslip.story.tsx
Labels: bug, :axis, :xy

#1679 build(react): allow `react@^17` as peer dependency
  packages/charts/package.json
  packages/charts/src/specs/specs_parser.tsx
  wiki/consuming.md
Labels: dependencies

#1708 fix(heatmap): don't render null values
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-heatmap-alpha-sorting-visually-looks-correct-1-snap.png
  packages/charts/src/chart_types/heatmap/scales/band_color_scale.ts
  packages/charts/src/chart_types/heatmap/state/selectors/get_heatmap_table.ts
  packages/charts/src/utils/common.ts
  storybook/stories/heatmap/7_sorting.story.tsx
  storybook/stories/heatmap/heatmap.stories.tsx
Labels: bug, :data, :heatmap

#1696 refactor(scales): use specific scales instead of generics
  integration/tests/__image_snapshots__/annotations-stories-test-ts-annotations-stories-render-with-zero-domain-or-fit-to-domain-does-not-show-annotation-with-y-domain-is-0-0-and-y-0-and-y-1-specified-1-snap.png
  integration/tests/__image_snapshots__/annotations-stories-test-ts-annotations-stories-render-with-zero-domain-or-fit-to-domain-does-not-show-annotation-with-y-domain-is-20-20-and-y-0-and-y-1-values-are-specified-1-snap.png
  integration/tests/__image_snapshots__/annotations-stories-test-ts-annotations-stories-render-with-zero-domain-or-fit-to-domain-show-annotation-when-y-domain-fit-is-true-1-snap.png
  integration/tests/__image_snapshots__/annotations-stories-test-ts-annotations-stories-render-with-zero-domain-or-fit-to-domain-show-annotation-when-y-domain-is-0-0-1-snap.png
  integration/tests/__image_snapshots__/axis-stories-test-ts-axis-stories-renders-multilayer-time-axis-with-a-single-point-and-a-degenerate-zero-width-domain-1-snap.png
  package.json
  packages/charts/package.json
  packages/charts/src/chart_types/xy_chart/annotations/line/dimensions.ts
  packages/charts/src/chart_types/xy_chart/annotations/rect/dimensions.ts
  packages/charts/src/chart_types/xy_chart/annotations/utils.ts
  packages/charts/src/chart_types/xy_chart/axes/timeslip/multilayer_ticks.ts
  packages/charts/src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
  packages/charts/src/chart_types/xy_chart/crosshair/crosshair_utils.ts
  packages/charts/src/chart_types/xy_chart/rendering/__snapshots__/rendering.bands.test.ts.snap
  packages/charts/src/chart_types/xy_chart/rendering/area.ts
  packages/charts/src/chart_types/xy_chart/rendering/bars.ts
  packages/charts/src/chart_types/xy_chart/rendering/bubble.ts
  packages/charts/src/chart_types/xy_chart/rendering/line.ts
  packages/charts/src/chart_types/xy_chart/rendering/points.ts
  packages/charts/src/chart_types/xy_chart/rendering/rendering.areas.test.ts
  packages/charts/src/chart_types/xy_chart/rendering/rendering.lines.test.ts
  packages/charts/src/chart_types/xy_chart/rendering/utils.ts
  packages/charts/src/chart_types/xy_chart/state/__snapshots__/chart_state.debug.test.ts.snap
  packages/charts/src/chart_types/xy_chart/state/chart_state.timescales.test.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/compute_axis_ticks_dimensions.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/compute_small_multiple_scales.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/get_brush_area.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_band.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/get_elements_at_cursor_pos.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/get_projected_pointer_position.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/get_projected_scaled_values.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/get_tooltip_position.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/on_pointer_move_caller.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/visible_ticks.ts
  packages/charts/src/chart_types/xy_chart/state/utils/types.ts
  packages/charts/src/chart_types/xy_chart/state/utils/utils.ts
  packages/charts/src/chart_types/xy_chart/utils/axis_utils.test.ts
  packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
  packages/charts/src/chart_types/xy_chart/utils/scales.test.ts
  packages/charts/src/chart_types/xy_chart/utils/scales.ts
  packages/charts/src/mocks/scale/scale.ts
  packages/charts/src/scales/index.ts
  packages/charts/src/scales/scale_band.test.ts
  packages/charts/src/scales/scale_band.ts
  packages/charts/src/scales/scale_continuous.test.ts
  packages/charts/src/scales/scale_continuous.ts
  packages/charts/src/scales/scales.test.ts
  packages/charts/src/scales/types.ts
  packages/charts/src/state/selectors/is_external_tooltip_visible.ts
  packages/charts/src/utils/events.ts
  yarn.lock
Labels: :data, :xy, :build

#1713 chore: pick up perf and refactor commits as patch release
  .releaserc.js
  package.json
  yarn.lock
Labels: chore, :build

#1714 build: update missing semantic-release deps
  package.json
  yarn.lock
Labels: :build

#1723 fix(heatmap): correctly compute vertical axis width max size
  packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
  packages/charts/src/chart_types/heatmap/state/selectors/compute_chart_dimensions.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/text.ts
  storybook/stories/heatmap/5_theming.story.tsx
Labels: bug, :styling, :heatmap

#1729 fix(example): make events work in the composable story
  storybook/stories/composable/1_basic.story.tsx
Labels: bug, visual testing

#1730 fix(events): remove async callbacks from code
  packages/charts/src/chart_types/xy_chart/state/selectors/on_projection_area_caller.ts
  packages/charts/src/components/chart_container.tsx
  packages/charts/src/components/chart_status.tsx
Labels: enhancement, :interactions, :refactor
