Repository elastic/elastic-charts, pull requests merged in 2022-05, with the labels that each got.

#1665 fix(animations): initialize all conditionalized props
  packages/charts/src/chart_types/xy_chart/annotations/rect/dimensions.ts
  packages/charts/src/chart_types/xy_chart/annotations/rect/types.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/animations/README.md
  packages/charts/src/chart_types/xy_chart/renderer/canvas/animations/index.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/annotations/lines.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/annotations/rect.ts
  packages/charts/src/mocks/annotations/annotations.ts
Labels: :interactions, :xy

#1676 feat(flame): search and other utilities
  .eslintrc.js
  integration/jest_env_setup.ts
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-flame-alpha-cpu-profile-gl-flame-chart-visually-looks-correct-1-snap.png
  packages/charts/src/chart_types/flame_chart/flame_chart.tsx
  packages/charts/src/chart_types/flame_chart/render/common.ts
  packages/charts/src/chart_types/flame_chart/render/draw_a_frame.ts
  packages/charts/src/chart_types/flame_chart/render/draw_canvas.ts
  packages/charts/src/chart_types/flame_chart/render/draw_webgl.ts
  packages/charts/src/chart_types/flame_chart/render/ensure_webgl.ts
  packages/charts/src/chart_types/flame_chart/types.ts
  packages/charts/src/common/kingly.ts
  packages/charts/src/common/webgl_constants.ts
  packages/charts/src/components/chart_container.tsx
  scripts/setup_enzyme.ts
  scripts/webgl_context_mock.ts
Labels: enhancement, :interactions, :flamegraph

#1678 feat(flame): minimap pan
  integration/tests/__image_snapshots__/all-test-ts-baseline-visual-tests-for-all-stories-flame-alpha-cpu-profile-gl-flame-chart-visually-looks-correct-1-snap.png
  packages/charts/src/chart_types/flame_chart/flame_chart.tsx
  packages/charts/src/chart_types/flame_chart/render/common.ts
  packages/charts/src/chart_types/flame_chart/render/draw_a_frame.ts
  packages/charts/src/chart_types/flame_chart/render/draw_canvas.ts
Labels: enhancement, :flamegraph

#1682 feat(flame): context loss handling
  packages/charts/src/chart_types/flame_chart/flame_chart.tsx
  packages/charts/src/chart_types/flame_chart/render/draw_canvas.ts
  packages/charts/src/chart_types/flame_chart/render/ensure_webgl.ts
  packages/charts/src/chart_types/flame_chart/shaders.ts
  packages/charts/src/common/default_theme_attributes.ts
  packages/charts/src/common/kingly.ts
  packages/charts/src/state/selectors/get_legend_size.ts
Labels: enhancement, chore, :flamegraph

#1690 performance(flame): uniform buffers and shader rework
  packages/charts/src/chart_types/flame_chart/flame_chart.tsx
  packages/charts/src/chart_types/flame_chart/render/draw_a_frame.ts
  packages/charts/src/chart_types/flame_chart/render/draw_canvas.ts
  packages/charts/src/chart_types/flame_chart/render/draw_webgl.ts
  packages/charts/src/chart_types/flame_chart/render/ensure_webgl.ts
  packages/charts/src/chart_types/flame_chart/render/upload_to_webgl.ts
  packages/charts/src/chart_types/flame_chart/shaders.ts
  packages/charts/src/chart_types/flame_chart/types.ts
  packages/charts/src/common/kingly.ts
Labels: :performance, :flamegraph, :refactor
