Repository elastic/elastic-charts, pull requests merged in 2023-11, with the labels that each got.

#2227 fix: clamp brushing min of last bucket
  packages/charts/src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts
Labels: bug, :interactions, :xy

#2225 fix(BarSeries): ignore histogram mode in determining stacked series
  e2e/screenshots/all.test.ts-snapshots/baselines/bar-chart/test-histogram-mode-linear-chrome-linux.png
  e2e/screenshots/all.test.ts-snapshots/baselines/bar-chart/test-histogram-mode-ordinal-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/enable-histogram-mode-is-false/rotation-0-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/enable-histogram-mode-is-false/rotation-180-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/enable-histogram-mode-is-false/rotation-90-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/enable-histogram-mode-is-false/rotation-negative-90-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/enable-histogram-mode-is-true/rotation-0-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/enable-histogram-mode-is-true/rotation-180-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/enable-histogram-mode-is-true/rotation-90-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/enable-histogram-mode-is-true/rotation-negative-90-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/point-alignment/center-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/point-alignment/end-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-linear/point-alignment/start-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-ordinal/enable-histogram-mode-is-false-has-histogram-bar-series-is-false/rotation-0-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-ordinal/enable-histogram-mode-is-false-has-histogram-bar-series-is-false/rotation-180-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-ordinal/enable-histogram-mode-is-false-has-histogram-bar-series-is-false/rotation-90-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-ordinal/enable-histogram-mode-is-false-has-histogram-bar-series-is-false/rotation-negative-90-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-ordinal/enable-histogram-mode-is-true-has-histogram-bar-series-is-true/rotation-0-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-ordinal/enable-histogram-mode-is-true-has-histogram-bar-series-is-true/rotation-180-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-ordinal/enable-histogram-mode-is-true-has-histogram-bar-series-is-true/rotation-90-chrome-linux.png
  e2e/screenshots/bar_stories.test.ts-snapshots/bar-series-stories/test-histogram-mode-ordinal/enable-histogram-mode-is-true-has-histogram-bar-series-is-true/rotation-negative-90-chrome-linux.png
  e2e/tests/bar_stories.test.ts
  packages/charts/api/charts.api.md
  packages/charts/src/chart_types/xy_chart/domains/y_domain.ts
  packages/charts/src/chart_types/xy_chart/legend/legend.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/count_bars_in_cluster.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts
  packages/charts/src/chart_types/xy_chart/state/utils/utils.ts
  packages/charts/src/chart_types/xy_chart/tooltip/tooltip.test.ts
  packages/charts/src/chart_types/xy_chart/tooltip/tooltip.ts
  packages/charts/src/chart_types/xy_chart/utils/series.test.ts
  packages/charts/src/chart_types/xy_chart/utils/series.ts
  packages/charts/src/chart_types/xy_chart/utils/specs.ts
  storybook/stories/axes/11_fit_domain_extent.story.tsx
  storybook/stories/bar/41_test_histogram_linear.story.tsx
  storybook/stories/bar/42_test_histogram_ordinal.story.tsx
  storybook/stories/components/tooltip/10_cartesian_chart.story.tsx
  storybook/stories/utils/knobs/custom.ts
Labels: bug, :data, :xy

#2228 fix: `onRenderChange` callback trigger on resize
  e2e/screenshots/all.test.ts-snapshots/baselines/test-cases/resize-debounce-chrome-linux.png
  packages/charts/api/charts.api.md
  packages/charts/src/components/__snapshots__/chart.test.tsx.snap
  packages/charts/src/components/chart_resizer.tsx
  packages/charts/src/components/chart_status.tsx
  packages/charts/src/specs/constants.ts
  packages/charts/src/specs/settings.tsx
  packages/charts/src/state/chart_state.ts
  storybook/stories/test_cases/10_highlighter_z_index.story.tsx
  storybook/stories/test_cases/11_resize_debounce.story.tsx
  storybook/stories/test_cases/test_cases.stories.tsx
Labels: bug, :chart, :xy, :all

#2234 test: add resize config for easy story and e2e resizing
  e2e/page_objects/common.ts
  e2e/tests/tooltip.test.ts
  e2e_server/server/generate/vrt_page_template.js
  e2e_server/server/mocks/use_global_parameters.ts
  storybook/stories/metric/1_basic.story.tsx
  storybook/stories/test_cases/11_resize_debounce.story.tsx
  storybook/story_wrapper.tsx
  storybook/style.scss
  storybook/types.ts
Labels: :docs, :ci

#2239 ci: fix vrt-specific style issues
  storybook/style.scss
Labels: :ci

#2237 docs: improve metric story
  e2e/screenshots/all.test.ts-snapshots/baselines/metric-alpha/grid-chrome-linux.png
  e2e/screenshots/chart.test.ts-snapshots/chart/sizing/should-accommodate-chart-title-and-description-metric-sm-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-horizontal-progress-bar-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-horizontal-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-no-progress-bar-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-no-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-vertical-progress-bar-in-dark-mode-chrome-linux.png
  storybook/stories/metric/2_grid.story.tsx
Labels: :docs, :metric

#2248 fix(metric): background color for bar with interactions
  e2e/page_objects/common.ts
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-horizontal/bullet-as-metric/should-render-with-negative-values-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-horizontal/bullet-as-metric/should-render-with-negative-values-reversed-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-horizontal/bullet-as-metric/should-render-with-positive-negative-values-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-horizontal/bullet-as-metric/should-render-with-positive-negative-values-reversed-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-horizontal/bullet-as-metric/should-render-with-positive-values-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-horizontal/bullet-as-metric/should-render-with-positive-values-reversed-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-two-thirds-circle/bullet-as-metric/should-render-with-negative-values-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-two-thirds-circle/bullet-as-metric/should-render-with-negative-values-reversed-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-two-thirds-circle/bullet-as-metric/should-render-with-positive-negative-values-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-two-thirds-circle/bullet-as-metric/should-render-with-positive-negative-values-reversed-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-two-thirds-circle/bullet-as-metric/should-render-with-positive-values-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-two-thirds-circle/bullet-as-metric/should-render-with-positive-values-reversed-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-vertical/bullet-as-metric/should-render-with-negative-values-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-vertical/bullet-as-metric/should-render-with-negative-values-reversed-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-vertical/bullet-as-metric/should-render-with-positive-negative-values-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-vertical/bullet-as-metric/should-render-with-positive-negative-values-reversed-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-vertical/bullet-as-metric/should-render-with-positive-values-chrome-linux.png
  e2e/screenshots/bullet_stories.test.ts-snapshots/bullet-stories/bullet-as-metric-vertical/bullet-as-metric/should-render-with-positive-values-reversed-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/dark-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/light-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/light-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/light-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/light-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/light-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/light-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/tests/metric_stories.test.ts
  e2e/tests/tooltip.test.ts
  packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
  packages/charts/src/chart_types/metric/renderer/dom/progress.tsx
  storybook/parameters.ts
Labels: bug, :styling, :metric

#2247 fix(metric): add option to set empty cell background color
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-with-empty-and-missing-background-colors-chrome-linux.png
  e2e/tests/metric_stories.test.ts
  packages/charts/api/charts.api.md
  packages/charts/src/chart_types/bullet_graph/renderer/canvas/index.tsx
  packages/charts/src/chart_types/metric/renderer/dom/index.tsx
  packages/charts/src/utils/themes/dark_theme.ts
  packages/charts/src/utils/themes/legacy_dark_theme.ts
  packages/charts/src/utils/themes/legacy_light_theme.ts
  packages/charts/src/utils/themes/light_theme.ts
  packages/charts/src/utils/themes/theme.ts
  storybook/parameters.ts
  storybook/stories/metric/2_grid.story.tsx
Labels: :styling, :metric

#2249 fix(metric): background color for bar with interactions (#2248) [61.0.x]
  e2e/page_objects/common.ts
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/dark-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/light-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/light-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/light-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/light-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/light-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/light-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/tests/metric_stories.test.ts
  e2e/tests/tooltip.test.ts
  packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
  packages/charts/src/chart_types/metric/renderer/dom/progress.tsx
  storybook/parameters.ts
Labels: backport

#2250 fix(metric): add option to set empty cell background color (#2247) [61.0.x]
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-with-empty-and-missing-background-colors-chrome-linux.png
  e2e/tests/metric_stories.test.ts
  packages/charts/api/charts.api.md
  packages/charts/src/chart_types/metric/renderer/dom/index.tsx
  packages/charts/src/utils/themes/dark_theme.ts
  packages/charts/src/utils/themes/legacy_dark_theme.ts
  packages/charts/src/utils/themes/legacy_light_theme.ts
  packages/charts/src/utils/themes/light_theme.ts
  packages/charts/src/utils/themes/theme.ts
  storybook/parameters.ts
  storybook/stories/metric/2_grid.story.tsx
Labels: backport

#2255 fix(metric): background colors and sparkline rendering
  e2e/screenshots/all.test.ts-snapshots/baselines/metric-alpha/grid-chrome-linux.png
  e2e/screenshots/chart.test.ts-snapshots/chart/sizing/should-accommodate-chart-title-and-description-metric-sm-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/should-render-with-blended-background-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/should-render-with-blended-background-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/should-render-with-blended-background-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-horizontal-progress-bar-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-horizontal-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-no-progress-bar-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-no-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-vertical-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-with-empty-and-missing-background-colors-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/text-value-with-trend-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/value-icon-and-value-color-chrome-linux.png
  e2e/tests/metric_stories.test.ts
  packages/charts/api/charts.api.md
  packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
  packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
  packages/charts/src/chart_types/metric/specs/index.ts
  packages/charts/src/common/fill_text_color.ts
  packages/charts/src/utils/themes/theme.ts
  storybook/stories/metric/1_basic.story.tsx
Labels: bug, :styling, :metric

#2257 fix(metric): background colors and sparkline rendering (#2255) [61.0.x]
  e2e/screenshots/all.test.ts-snapshots/baselines/metric-alpha/grid-chrome-linux.png
  e2e/screenshots/chart.test.ts-snapshots/chart/sizing/should-accommodate-chart-title-and-description-metric-sm-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-bar-type/should-render-with-blended-background-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-none-type/should-render-with-blended-background-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/dark-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-click-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-hover-interaction-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/light-theme/should-render-metric-with-transparent-bg-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/metric-trend-type/should-render-with-blended-background-color-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-horizontal-progress-bar-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-horizontal-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-no-progress-bar-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-no-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-vertical-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-with-empty-and-missing-background-colors-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/text-value-with-trend-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/value-icon-and-value-color-chrome-linux.png
  e2e/tests/metric_stories.test.ts
  packages/charts/api/charts.api.md
  packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
  packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
  packages/charts/src/chart_types/metric/specs/index.ts
  packages/charts/src/common/fill_text_color.ts
  packages/charts/src/utils/themes/theme.ts
  storybook/stories/metric/1_basic.story.tsx
Labels: backport

#2261 feat: increase tooltip width to 500px and truncate items to 2 lines
  e2e/screenshots/legend_stories.test.ts-snapshots/legend-stories/should-break-multiline-legends-with-long-url-characters-chrome-linux.png
  e2e/screenshots/tooltip.test.ts-snapshots/tooltip/chart-types/flamegraph/hide-prompt-with-no-actions-chrome-linux.png
  e2e/screenshots/tooltip.test.ts-snapshots/tooltip/chart-types/flamegraph/pinning-with-selection-chrome-linux.png
  e2e/screenshots/tooltip.test.ts-snapshots/tooltip/chart-types/flamegraph/show-prompt-with-actions-chrome-linux.png
  e2e/screenshots/tooltip.test.ts-snapshots/tooltip/chart-types/partition/pinning-with-selection-chrome-linux.png
  packages/charts/src/chart_types/metric/renderer/dom/_text.scss
  packages/charts/src/components/_mixins.scss
  packages/charts/src/components/tooltip/components/_tooltip.scss
  packages/charts/src/components/tooltip/placement.ts
  packages/charts/src/utils/themes/dark_theme.ts
  packages/charts/src/utils/themes/legacy_dark_theme.ts
  packages/charts/src/utils/themes/legacy_light_theme.ts
  packages/charts/src/utils/themes/light_theme.ts
Labels: enhancement, :tooltip, :all

#2260 fix(partition): zero value sectors cause max stack call
  packages/charts/src/chart_types/partition_chart/layout/utils/treemap.ts
  packages/charts/src/chart_types/partition_chart/partition.test.tsx
Labels: bug, :data, :partition

#2262 fix(theme): legacy margins
  packages/charts/src/utils/themes/legacy_dark_theme.ts
  packages/charts/src/utils/themes/legacy_light_theme.ts
  packages/charts/src/utils/themes/theme_common.ts
Labels: :styling

#2263 fix(theme): legacy margins (#2262) [61.0.x]
  packages/charts/src/utils/themes/legacy_dark_theme.ts
  packages/charts/src/utils/themes/legacy_light_theme.ts
  packages/charts/src/utils/themes/theme_common.ts
Labels: backport
