Repository elastic/elastic-charts, pull requests merged in 2023-09, with the labels that each got.

#2165 fix: update font family
  packages/charts/src/common/default_theme_attributes.ts
Labels: enhancement, :styling, :all

#2167 ci: fix linting ci check for deleted files
  .buildkite/scripts/steps/eslint.ts
  .buildkite/utils/github.ts
Labels: :ci

#2164 feat: add locale prop to Settings
  packages/charts/api/charts.api.md
  packages/charts/src/chart_types/heatmap/scales/band_color_scale.ts
  packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts
  packages/charts/src/chart_types/heatmap/state/selectors/get_heatmap_table.ts
  packages/charts/src/chart_types/metric/renderer/dom/index.tsx
  packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
  packages/charts/src/chart_types/metric/renderer/dom/text.tsx
  packages/charts/src/chart_types/partition_chart/state/selectors/compute_legend.ts
  packages/charts/src/chart_types/partition_chart/state/selectors/tree.ts
  packages/charts/src/chart_types/timeslip/timeslip/config.ts
  packages/charts/src/chart_types/timeslip/timeslip/render/annotations/time_unit.ts
  packages/charts/src/chart_types/xy_chart/axes/timeslip/continuous_time_rasters.ts
  packages/charts/src/chart_types/xy_chart/axes/timeslip/locale_translations.ts
  packages/charts/src/chart_types/xy_chart/axes/timeslip/multilayer_ticks.ts
  packages/charts/src/chart_types/xy_chart/crosshair/crosshair_utils.linear_snap.test.ts
  packages/charts/src/chart_types/xy_chart/crosshair/crosshair_utils.ordinal_snap.test.ts
  packages/charts/src/chart_types/xy_chart/domains/x_domain.test.ts
  packages/charts/src/chart_types/xy_chart/domains/x_domain.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/panels/panels.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/panels/title.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/renderers.ts
  packages/charts/src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
  packages/charts/src/chart_types/xy_chart/state/selectors/compute_series_domains.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
  packages/charts/src/chart_types/xy_chart/state/selectors/visible_ticks.ts
  packages/charts/src/chart_types/xy_chart/state/utils/utils.test.ts
  packages/charts/src/chart_types/xy_chart/state/utils/utils.ts
  packages/charts/src/common/predicate.ts
  packages/charts/src/components/__snapshots__/chart.test.tsx.snap
  packages/charts/src/specs/constants.ts
  packages/charts/src/specs/settings.tsx
  packages/charts/src/utils/domain.test.ts
  packages/charts/src/utils/domain.ts
  packages/charts/src/utils/text/wrap.ts
  storybook/stories/utils/text/1_wrap.story.tsx
Labels: enhancement, :i18n, :all

#2169 fix(tooltip): rendering in react v18
  e2e/screenshots/all.test.ts-snapshots/baselines/annotations-lines/advanced-markers-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-bottom/rotation-0/renders-marker-annotation-within-chart-canvas-metric-30-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-bottom/rotation-90/renders-marker-annotation-within-chart-canvas-metric-0-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-left/rotation-0/renders-marker-annotation-within-chart-canvas-metric-15-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-left/rotation-180/renders-marker-annotation-within-chart-canvas-metric-15-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-left/rotation-90/renders-marker-annotation-within-chart-canvas-metric-15-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-left/rotation-negative-90/renders-marker-annotation-within-chart-canvas-metric-15-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-right/rotation-0/renders-marker-annotation-within-chart-canvas-metric-15-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-right/rotation-180/renders-marker-annotation-within-chart-canvas-metric-15-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-right/rotation-90/renders-marker-annotation-within-chart-canvas-metric-15-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-right/rotation-negative-90/renders-marker-annotation-within-chart-canvas-metric-15-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-top/rotation-0/renders-marker-annotation-within-chart-canvas-metric-30-chrome-linux.png
  e2e/screenshots/annotations_stories.test.ts-snapshots/annotations-stories/advanced-markers/annotation-marker-side-top/rotation-90/renders-marker-annotation-within-chart-canvas-metric-0-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-chart/rotation-0/placement-bottom/shows-tooltip-in-top-left-corner-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-chart/rotation-0/placement-top/shows-tooltip-in-bottom-left-corner-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-chart/rotation-180/placement-bottom/shows-tooltip-in-top-left-corner-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-chart/rotation-180/placement-top/shows-tooltip-in-bottom-left-corner-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-default/rotation-0/placement-bottom/shows-tooltip-in-top-left-corner-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-default/rotation-0/placement-top/shows-tooltip-in-bottom-left-corner-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-default/rotation-0/placement-top/shows-tooltip-in-top-left-corner-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-default/rotation-180/placement-bottom/shows-tooltip-in-top-left-corner-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-default/rotation-180/placement-top/shows-tooltip-in-bottom-left-corner-chrome-linux.png
  e2e/screenshots/interactions.test.ts-snapshots/interactions/tooltips/positioning/boundary-el-default/rotation-180/placement-top/shows-tooltip-in-top-left-corner-chrome-linux.png
  packages/charts/package.json
  packages/charts/src/components/portal/tooltip_portal.tsx
  yarn.lock
Labels: :tooltip, dependencies, :all
