Repository elastic/elastic-charts, pull requests merged in 2024-07, with the labels that each got.

#2474 fix: (Legend values) percentage formatter should be distict from tick formatter
  e2e/screenshots/legend_stories.test.ts-snapshots/legend-stories/legend-tabular-data/should-correctly-display-current-and-last-value-median-values-chrome-linux.png
  e2e/screenshots/legend_stories.test.ts-snapshots/legend-stories/legend-tabular-data/should-correctly-display-difference-percent-values-chrome-linux.png
  e2e/screenshots/legend_stories.test.ts-snapshots/legend-stories/legend-tabular-data/should-correctly-display-last-non-null-value-values-chrome-linux.png
  e2e/screenshots/legend_stories.test.ts-snapshots/legend-stories/legend-tabular-data/should-correctly-display-long-copy-dataset-dataset-chrome-linux.png
  e2e/screenshots/legend_stories.test.ts-snapshots/legend-stories/legend-tabular-data/should-correctly-display-median-values-chrome-linux.png
  e2e/screenshots/legend_stories.test.ts-snapshots/legend-stories/legend-tabular-data/should-correctly-display-short-copy-dataset-dataset-chrome-linux.png
  e2e/tests/legend_stories.test.ts
  packages/charts/src/chart_types/xy_chart/state/utils/get_legend_values.ts
  packages/charts/src/components/legend/utils.ts
  packages/charts/src/state/selectors/get_legend_table_size.ts
  packages/charts/src/utils/data_samples/test_dataset.ts
  storybook/stories/legend/17_tabular_data.story.tsx
Labels: :legend

#2482 docs: remove reset styles in storybook
  e2e/screenshots/legend_stories.test.ts-snapshots/legend-stories/should-render-color-picker-on-mouse-click-chrome-linux.png
  storybook/style.scss
Labels: :docs

#2490 fix(metric): icon alignment defaults (#2489) [66.0.x]
  e2e/screenshots/all.test.ts-snapshots/baselines/metric-alpha/grid-chrome-linux.png
  e2e/screenshots/chart.test.ts-snapshots/chart/sizing/should-accommodate-chart-title-and-description-metric-sm-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-horizontal-progress-bar-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-horizontal-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-no-progress-bar-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-no-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-vertical-progress-bar-in-dark-mode-chrome-linux.png
  e2e/screenshots/metric_stories.test.ts-snapshots/metric/should-render-with-empty-and-missing-background-colors-chrome-linux.png
  packages/charts/src/utils/themes/dark_theme.ts
  packages/charts/src/utils/themes/legacy_dark_theme.ts
  packages/charts/src/utils/themes/legacy_light_theme.ts
  packages/charts/src/utils/themes/light_theme.ts
Labels: backport
